codecov:
  require_ci_to_pass: yes
coverage:
  status:
    project:
      default: off
      carga:
        target: auto
        flags:
          - carga
      uris:
        target: auto
        flags:
          - uris
      discover:
        target: auto
        flags:
          - discover
      cron:
        target: auto
        flags:
          - cron
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false
  require_base: yes
  require_head: yes
  branches: null
flags:
  carga:
    paths:
      - API_CARGA
    carryforward: false
  uris:
    paths:
      - UrisFactory
    carryforward: false
  cron:
    paths:
      - CronConfigure
    carryforward: false
  discover:
    paths:
      - API_DISCOVER
    carryforward: false
