coverage:
  status:
    project:
      default:
        target: 70%
      APICARGA:
        target: 50%
       flags:
          - APICARGA
      URISFACTORY:
        target: 70%
        flags:
          - URISFACTORY
      DISCOVER:
        target: 70%
        flags:
          - DISCOVER
      CRON:
        target: 40%
        flags:
          - CRON
comment:
  layout: "reach, diff, flags, files"
  behavior: default
  require_changes: false  
  require_base: yes
  require_head: yes       
  branches: null
flags:
  APICARGA:
    paths:
      - API_CARGA
    carryforward: false
  URISFACTORY:
    paths:
      - UrisFactory
    carryforward: false
  CRON:
    paths:
      - CronConfigure
    carryforward: false
  DISCOVER:
    paths:
      - API_DISCOVER
    carryforward: false
