### YamlMime:ManagedReference
items:
- uid: API_DISCOVER.Models.Services.ConfigScopus
  commentId: T:API_DISCOVER.Models.Services.ConfigScopus
  id: ConfigScopus
  parent: API_DISCOVER.Models.Services
  children:
  - API_DISCOVER.Models.Services.ConfigScopus.Configuration
  - API_DISCOVER.Models.Services.ConfigScopus.GetScopusApiKey
  - API_DISCOVER.Models.Services.ConfigScopus.GetScopusUrl
  langs:
  - csharp
  - vb
  name: ConfigScopus
  nameWithType: ConfigScopus
  fullName: API_DISCOVER.Models.Services.ConfigScopus
  type: Class
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/Models/Services/ConfigScopus.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: ConfigScopus
    path: Models/Services/ConfigScopus.cs
    startLine: 14
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.Models.Services
  summary: "\nClase para obtener la configuración necesaria para el uso del API de SCOPUS\n"
  example: []
  syntax:
    content: public class ConfigScopus
    content.vb: Public Class ConfigScopus
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: API_DISCOVER.Models.Services.ConfigScopus.Configuration
  commentId: P:API_DISCOVER.Models.Services.ConfigScopus.Configuration
  id: Configuration
  parent: API_DISCOVER.Models.Services.ConfigScopus
  langs:
  - csharp
  - vb
  name: Configuration
  nameWithType: ConfigScopus.Configuration
  fullName: API_DISCOVER.Models.Services.ConfigScopus.Configuration
  type: Property
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/Models/Services/ConfigScopus.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: Configuration
    path: Models/Services/ConfigScopus.cs
    startLine: 16
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.Models.Services
  syntax:
    content: public IConfigurationRoot Configuration { get; set; }
    parameters: []
    return:
      type: Microsoft.Extensions.Configuration.IConfigurationRoot
    content.vb: Public Property Configuration As IConfigurationRoot
  overload: API_DISCOVER.Models.Services.ConfigScopus.Configuration*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: API_DISCOVER.Models.Services.ConfigScopus.GetScopusApiKey
  commentId: M:API_DISCOVER.Models.Services.ConfigScopus.GetScopusApiKey
  id: GetScopusApiKey
  parent: API_DISCOVER.Models.Services.ConfigScopus
  langs:
  - csharp
  - vb
  name: GetScopusApiKey()
  nameWithType: ConfigScopus.GetScopusApiKey()
  fullName: API_DISCOVER.Models.Services.ConfigScopus.GetScopusApiKey()
  type: Method
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/Models/Services/ConfigScopus.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: GetScopusApiKey
    path: Models/Services/ConfigScopus.cs
    startLine: 23
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.Models.Services
  summary: "\nObtiene el API key de Scopus\n"
  example: []
  syntax:
    content: public string GetScopusApiKey()
    return:
      type: System.String
    content.vb: Public Function GetScopusApiKey As String
  overload: API_DISCOVER.Models.Services.ConfigScopus.GetScopusApiKey*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: API_DISCOVER.Models.Services.ConfigScopus.GetScopusUrl
  commentId: M:API_DISCOVER.Models.Services.ConfigScopus.GetScopusUrl
  id: GetScopusUrl
  parent: API_DISCOVER.Models.Services.ConfigScopus
  langs:
  - csharp
  - vb
  name: GetScopusUrl()
  nameWithType: ConfigScopus.GetScopusUrl()
  fullName: API_DISCOVER.Models.Services.ConfigScopus.GetScopusUrl()
  type: Method
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/Models/Services/ConfigScopus.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: GetScopusUrl
    path: Models/Services/ConfigScopus.cs
    startLine: 48
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.Models.Services
  summary: "\nObtiene el url del API de Scopus\n"
  example: []
  syntax:
    content: public string GetScopusUrl()
    return:
      type: System.String
    content.vb: Public Function GetScopusUrl As String
  overload: API_DISCOVER.Models.Services.ConfigScopus.GetScopusUrl*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: API_DISCOVER.Models.Services
  commentId: N:API_DISCOVER.Models.Services
  name: API_DISCOVER.Models.Services
  nameWithType: API_DISCOVER.Models.Services
  fullName: API_DISCOVER.Models.Services
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: API_DISCOVER.Models.Services.ConfigScopus.Configuration*
  commentId: Overload:API_DISCOVER.Models.Services.ConfigScopus.Configuration
  name: Configuration
  nameWithType: ConfigScopus.Configuration
  fullName: API_DISCOVER.Models.Services.ConfigScopus.Configuration
- uid: Microsoft.Extensions.Configuration.IConfigurationRoot
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationRoot
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  name: IConfigurationRoot
  nameWithType: IConfigurationRoot
  fullName: Microsoft.Extensions.Configuration.IConfigurationRoot
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: true
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
- uid: API_DISCOVER.Models.Services.ConfigScopus.GetScopusApiKey*
  commentId: Overload:API_DISCOVER.Models.Services.ConfigScopus.GetScopusApiKey
  name: GetScopusApiKey
  nameWithType: ConfigScopus.GetScopusApiKey
  fullName: API_DISCOVER.Models.Services.ConfigScopus.GetScopusApiKey
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: API_DISCOVER.Models.Services.ConfigScopus.GetScopusUrl*
  commentId: Overload:API_DISCOVER.Models.Services.ConfigScopus.GetScopusUrl
  name: GetScopusUrl
  nameWithType: ConfigScopus.GetScopusUrl
  fullName: API_DISCOVER.Models.Services.ConfigScopus.GetScopusUrl
