### YamlMime:ManagedReference
items:
- uid: API_DISCOVER.ViewModels.ShapeConfigViewModel
  commentId: T:API_DISCOVER.ViewModels.ShapeConfigViewModel
  id: ShapeConfigViewModel
  parent: API_DISCOVER.ViewModels
  children:
  - API_DISCOVER.ViewModels.ShapeConfigViewModel.Name
  - API_DISCOVER.ViewModels.ShapeConfigViewModel.RepositoryID
  - API_DISCOVER.ViewModels.ShapeConfigViewModel.Shape
  - API_DISCOVER.ViewModels.ShapeConfigViewModel.ShapeConfigID
  langs:
  - csharp
  - vb
  name: ShapeConfigViewModel
  nameWithType: ShapeConfigViewModel
  fullName: API_DISCOVER.ViewModels.ShapeConfigViewModel
  type: Class
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/ViewModels/ShapeConfigViewModel.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: ShapeConfigViewModel
    path: ViewModels/ShapeConfigViewModel.cs
    startLine: 7
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.ViewModels
  syntax:
    content: >-
      [Display(Name = "Shape config")]

      public class ShapeConfigViewModel
    content.vb: >-
      <Display(Name:="Shape config")>

      Public Class ShapeConfigViewModel
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.ComponentModel.DataAnnotations.DisplayAttribute
    ctor: System.ComponentModel.DataAnnotations.DisplayAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Name
      type: System.String
      value: Shape config
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: API_DISCOVER.ViewModels.ShapeConfigViewModel.ShapeConfigID
  commentId: P:API_DISCOVER.ViewModels.ShapeConfigViewModel.ShapeConfigID
  id: ShapeConfigID
  parent: API_DISCOVER.ViewModels.ShapeConfigViewModel
  langs:
  - csharp
  - vb
  name: ShapeConfigID
  nameWithType: ShapeConfigViewModel.ShapeConfigID
  fullName: API_DISCOVER.ViewModels.ShapeConfigViewModel.ShapeConfigID
  type: Property
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/ViewModels/ShapeConfigViewModel.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: ShapeConfigID
    path: ViewModels/ShapeConfigViewModel.cs
    startLine: 11
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.ViewModels
  syntax:
    content: >-
      [Display(Name = "Identifier")]

      public Guid ShapeConfigID { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: >-
      <Display(Name:="Identifier")>

      Public Property ShapeConfigID As Guid
  overload: API_DISCOVER.ViewModels.ShapeConfigViewModel.ShapeConfigID*
  attributes:
  - type: System.ComponentModel.DataAnnotations.DisplayAttribute
    ctor: System.ComponentModel.DataAnnotations.DisplayAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Name
      type: System.String
      value: Identifier
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: API_DISCOVER.ViewModels.ShapeConfigViewModel.Name
  commentId: P:API_DISCOVER.ViewModels.ShapeConfigViewModel.Name
  id: Name
  parent: API_DISCOVER.ViewModels.ShapeConfigViewModel
  langs:
  - csharp
  - vb
  name: Name
  nameWithType: ShapeConfigViewModel.Name
  fullName: API_DISCOVER.ViewModels.ShapeConfigViewModel.Name
  type: Property
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/ViewModels/ShapeConfigViewModel.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: Name
    path: ViewModels/ShapeConfigViewModel.cs
    startLine: 13
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.ViewModels
  syntax:
    content: public string Name { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Name As String
  overload: API_DISCOVER.ViewModels.ShapeConfigViewModel.Name*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: API_DISCOVER.ViewModels.ShapeConfigViewModel.RepositoryID
  commentId: P:API_DISCOVER.ViewModels.ShapeConfigViewModel.RepositoryID
  id: RepositoryID
  parent: API_DISCOVER.ViewModels.ShapeConfigViewModel
  langs:
  - csharp
  - vb
  name: RepositoryID
  nameWithType: ShapeConfigViewModel.RepositoryID
  fullName: API_DISCOVER.ViewModels.ShapeConfigViewModel.RepositoryID
  type: Property
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/ViewModels/ShapeConfigViewModel.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: RepositoryID
    path: ViewModels/ShapeConfigViewModel.cs
    startLine: 14
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.ViewModels
  syntax:
    content: >-
      [Display(Name = "identificador del repositorio")]

      public Guid RepositoryID { get; set; }
    parameters: []
    return:
      type: System.Guid
    content.vb: >-
      <Display(Name:="identificador del repositorio")>

      Public Property RepositoryID As Guid
  overload: API_DISCOVER.ViewModels.ShapeConfigViewModel.RepositoryID*
  attributes:
  - type: System.ComponentModel.DataAnnotations.DisplayAttribute
    ctor: System.ComponentModel.DataAnnotations.DisplayAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Name
      type: System.String
      value: identificador del repositorio
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: API_DISCOVER.ViewModels.ShapeConfigViewModel.Shape
  commentId: P:API_DISCOVER.ViewModels.ShapeConfigViewModel.Shape
  id: Shape
  parent: API_DISCOVER.ViewModels.ShapeConfigViewModel
  langs:
  - csharp
  - vb
  name: Shape
  nameWithType: ShapeConfigViewModel.Shape
  fullName: API_DISCOVER.ViewModels.ShapeConfigViewModel.Shape
  type: Property
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/ViewModels/ShapeConfigViewModel.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: Shape
    path: ViewModels/ShapeConfigViewModel.cs
    startLine: 16
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.ViewModels
  syntax:
    content: public string Shape { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property Shape As String
  overload: API_DISCOVER.ViewModels.ShapeConfigViewModel.Shape*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: API_DISCOVER.ViewModels
  commentId: N:API_DISCOVER.ViewModels
  name: API_DISCOVER.ViewModels
  nameWithType: API_DISCOVER.ViewModels
  fullName: API_DISCOVER.ViewModels
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: API_DISCOVER.ViewModels.ShapeConfigViewModel.ShapeConfigID*
  commentId: Overload:API_DISCOVER.ViewModels.ShapeConfigViewModel.ShapeConfigID
  name: ShapeConfigID
  nameWithType: ShapeConfigViewModel.ShapeConfigID
  fullName: API_DISCOVER.ViewModels.ShapeConfigViewModel.ShapeConfigID
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: API_DISCOVER.ViewModels.ShapeConfigViewModel.Name*
  commentId: Overload:API_DISCOVER.ViewModels.ShapeConfigViewModel.Name
  name: Name
  nameWithType: ShapeConfigViewModel.Name
  fullName: API_DISCOVER.ViewModels.ShapeConfigViewModel.Name
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: API_DISCOVER.ViewModels.ShapeConfigViewModel.RepositoryID*
  commentId: Overload:API_DISCOVER.ViewModels.ShapeConfigViewModel.RepositoryID
  name: RepositoryID
  nameWithType: ShapeConfigViewModel.RepositoryID
  fullName: API_DISCOVER.ViewModels.ShapeConfigViewModel.RepositoryID
- uid: API_DISCOVER.ViewModels.ShapeConfigViewModel.Shape*
  commentId: Overload:API_DISCOVER.ViewModels.ShapeConfigViewModel.Shape
  name: Shape
  nameWithType: ShapeConfigViewModel.Shape
  fullName: API_DISCOVER.ViewModels.ShapeConfigViewModel.Shape
