openapi: 3.0.0
info:
  description: Servidor HTTP que ofrece una API para convertir XML CVN a tripletas
    ROH.
  title: Servicio conversión CVN-ROH
  version: af0908b
servers:
- url: http://localhost:5000/v1
paths:
  /convert:
    post:
      operationId: convert_post
      parameters:
      - description: ORCID de la persona del CVN a convertir
        explode: true
        in: query
        name: orcid
        required: true
        schema:
          type: string
        style: form
      - description: Formato de salida deseado
        explode: true
        in: query
        name: format
        required: false
        schema:
          default: xml
          enum:
          - xml
          - n3
          - turtle
          - nt
          - pretty-xml
          - trix
          - trig
          - nquads
          type: string
        style: form
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              format: binary
              type: string
        required: true
      responses:
        "200":
          description: Resultado de la conversión, en el formato que se haya pedido
            (xml por defecto)
        "500":
          description: Error de conversión (archivo demasiado grande/mal formateado)
            o del servidor en general.
        "422":
          description: Error de validación. Algún campo no se está incluyendo o se
            está incluyendo mal. Ver mensaje de respuesta
      summary: Convierte CVN XML a tripletas ROH
      x-openapi-router-controller: openapi_server.controllers.default_controller
components:
  schemas: {}
