### YamlMime:ManagedReference
items:
- uid: UrisFactory.Models.ConfigEntities
  commentId: N:UrisFactory.Models.ConfigEntities
  id: UrisFactory.Models.ConfigEntities
  children:
  - UrisFactory.Models.ConfigEntities.Characters
  - UrisFactory.Models.ConfigEntities.Component
  - UrisFactory.Models.ConfigEntities.ResourcesClass
  - UrisFactory.Models.ConfigEntities.UriComponentsList
  - UrisFactory.Models.ConfigEntities.UriStructure
  - UrisFactory.Models.ConfigEntities.UriStructureGeneral
  langs:
  - csharp
  - vb
  name: UrisFactory.Models.ConfigEntities
  nameWithType: UrisFactory.Models.ConfigEntities
  fullName: UrisFactory.Models.ConfigEntities
  type: Namespace
  assemblies:
  - UrisFactory
references:
- uid: UrisFactory.Models.ConfigEntities.Characters
  commentId: T:UrisFactory.Models.ConfigEntities.Characters
  name: Characters
  nameWithType: Characters
  fullName: UrisFactory.Models.ConfigEntities.Characters
- uid: UrisFactory.Models.ConfigEntities.Component
  commentId: T:UrisFactory.Models.ConfigEntities.Component
  name: Component
  nameWithType: Component
  fullName: UrisFactory.Models.ConfigEntities.Component
- uid: UrisFactory.Models.ConfigEntities.ResourcesClass
  commentId: T:UrisFactory.Models.ConfigEntities.ResourcesClass
  parent: UrisFactory.Models.ConfigEntities
  name: ResourcesClass
  nameWithType: ResourcesClass
  fullName: UrisFactory.Models.ConfigEntities.ResourcesClass
- uid: UrisFactory.Models.ConfigEntities.UriComponentsList
  commentId: T:UrisFactory.Models.ConfigEntities.UriComponentsList
  name: UriComponentsList
  nameWithType: UriComponentsList
  fullName: UrisFactory.Models.ConfigEntities.UriComponentsList
- uid: UrisFactory.Models.ConfigEntities.UriStructure
  commentId: T:UrisFactory.Models.ConfigEntities.UriStructure
  parent: UrisFactory.Models.ConfigEntities
  name: UriStructure
  nameWithType: UriStructure
  fullName: UrisFactory.Models.ConfigEntities.UriStructure
- uid: UrisFactory.Models.ConfigEntities.UriStructureGeneral
  commentId: T:UrisFactory.Models.ConfigEntities.UriStructureGeneral
  parent: UrisFactory.Models.ConfigEntities
  name: UriStructureGeneral
  nameWithType: UriStructureGeneral
  fullName: UrisFactory.Models.ConfigEntities.UriStructureGeneral
- uid: UrisFactory.Models.ConfigEntities
  commentId: N:UrisFactory.Models.ConfigEntities
  name: UrisFactory.Models.ConfigEntities
  nameWithType: UrisFactory.Models.ConfigEntities
  fullName: UrisFactory.Models.ConfigEntities
