### YamlMime:ManagedReference
items:
- uid: UrisFactory.Models.ConfigEntities.ResourcesClass
  commentId: T:UrisFactory.Models.ConfigEntities.ResourcesClass
  id: ResourcesClass
  parent: UrisFactory.Models.ConfigEntities
  children:
  - UrisFactory.Models.ConfigEntities.ResourcesClass.LabelResourceClass
  - UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceClass
  - UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceURI
  langs:
  - csharp
  - vb
  name: ResourcesClass
  nameWithType: ResourcesClass
  fullName: UrisFactory.Models.ConfigEntities.ResourcesClass
  type: Class
  source:
    remote:
      path: UrisFactory/UrisAutoGenerator/Models/ConfigEntities/ResourcesClass.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: ResourcesClass
    path: Models/ConfigEntities/ResourcesClass.cs
    startLine: 3
  assemblies:
  - UrisFactory
  namespace: UrisFactory.Models.ConfigEntities
  syntax:
    content: public class ResourcesClass
    content.vb: Public Class ResourcesClass
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceClass
  commentId: P:UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceClass
  id: ResourceClass
  parent: UrisFactory.Models.ConfigEntities.ResourcesClass
  langs:
  - csharp
  - vb
  name: ResourceClass
  nameWithType: ResourcesClass.ResourceClass
  fullName: UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceClass
  type: Property
  source:
    remote:
      path: UrisFactory/UrisAutoGenerator/Models/ConfigEntities/ResourcesClass.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: ResourceClass
    path: Models/ConfigEntities/ResourcesClass.cs
    startLine: 5
  assemblies:
  - UrisFactory
  namespace: UrisFactory.Models.ConfigEntities
  syntax:
    content: public string ResourceClass { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ResourceClass As String
  overload: UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceClass*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: UrisFactory.Models.ConfigEntities.ResourcesClass.LabelResourceClass
  commentId: P:UrisFactory.Models.ConfigEntities.ResourcesClass.LabelResourceClass
  id: LabelResourceClass
  parent: UrisFactory.Models.ConfigEntities.ResourcesClass
  langs:
  - csharp
  - vb
  name: LabelResourceClass
  nameWithType: ResourcesClass.LabelResourceClass
  fullName: UrisFactory.Models.ConfigEntities.ResourcesClass.LabelResourceClass
  type: Property
  source:
    remote:
      path: UrisFactory/UrisAutoGenerator/Models/ConfigEntities/ResourcesClass.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: LabelResourceClass
    path: Models/ConfigEntities/ResourcesClass.cs
    startLine: 6
  assemblies:
  - UrisFactory
  namespace: UrisFactory.Models.ConfigEntities
  syntax:
    content: public string LabelResourceClass { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property LabelResourceClass As String
  overload: UrisFactory.Models.ConfigEntities.ResourcesClass.LabelResourceClass*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceURI
  commentId: P:UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceURI
  id: ResourceURI
  parent: UrisFactory.Models.ConfigEntities.ResourcesClass
  langs:
  - csharp
  - vb
  name: ResourceURI
  nameWithType: ResourcesClass.ResourceURI
  fullName: UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceURI
  type: Property
  source:
    remote:
      path: UrisFactory/UrisAutoGenerator/Models/ConfigEntities/ResourcesClass.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: ResourceURI
    path: Models/ConfigEntities/ResourcesClass.cs
    startLine: 7
  assemblies:
  - UrisFactory
  namespace: UrisFactory.Models.ConfigEntities
  syntax:
    content: public string ResourceURI { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property ResourceURI As String
  overload: UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceURI*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: UrisFactory.Models.ConfigEntities
  commentId: N:UrisFactory.Models.ConfigEntities
  name: UrisFactory.Models.ConfigEntities
  nameWithType: UrisFactory.Models.ConfigEntities
  fullName: UrisFactory.Models.ConfigEntities
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceClass*
  commentId: Overload:UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceClass
  name: ResourceClass
  nameWithType: ResourcesClass.ResourceClass
  fullName: UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceClass
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: UrisFactory.Models.ConfigEntities.ResourcesClass.LabelResourceClass*
  commentId: Overload:UrisFactory.Models.ConfigEntities.ResourcesClass.LabelResourceClass
  name: LabelResourceClass
  nameWithType: ResourcesClass.LabelResourceClass
  fullName: UrisFactory.Models.ConfigEntities.ResourcesClass.LabelResourceClass
- uid: UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceURI*
  commentId: Overload:UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceURI
  name: ResourceURI
  nameWithType: ResourcesClass.ResourceURI
  fullName: UrisFactory.Models.ConfigEntities.ResourcesClass.ResourceURI
