### YamlMime:ManagedReference
items:
- uid: UrisFactory.Models.ConfigEntities.UriComponentsList
  commentId: T:UrisFactory.Models.ConfigEntities.UriComponentsList
  id: UriComponentsList
  parent: UrisFactory.Models.ConfigEntities
  children:
  - UrisFactory.Models.ConfigEntities.UriComponentsList.Base
  - UrisFactory.Models.ConfigEntities.UriComponentsList.Character
  - UrisFactory.Models.ConfigEntities.UriComponentsList.DefaultParameters
  - UrisFactory.Models.ConfigEntities.UriComponentsList.Identifier
  - UrisFactory.Models.ConfigEntities.UriComponentsList.ResourceClass
  langs:
  - csharp
  - vb
  name: UriComponentsList
  nameWithType: UriComponentsList
  fullName: UrisFactory.Models.ConfigEntities.UriComponentsList
  type: Class
  source:
    remote:
      path: UrisFactory/UrisAutoGenerator/Models/ConfigEntities/UriComponentsList.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: UriComponentsList
    path: Models/ConfigEntities/UriComponentsList.cs
    startLine: 6
  assemblies:
  - UrisFactory
  namespace: UrisFactory.Models.ConfigEntities
  syntax:
    content: public static class UriComponentsList
    content.vb: Public Module UriComponentsList
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - static
  - class
  modifiers.vb:
  - Public
  - Module
- uid: UrisFactory.Models.ConfigEntities.UriComponentsList.Base
  commentId: F:UrisFactory.Models.ConfigEntities.UriComponentsList.Base
  id: Base
  parent: UrisFactory.Models.ConfigEntities.UriComponentsList
  langs:
  - csharp
  - vb
  name: Base
  nameWithType: UriComponentsList.Base
  fullName: UrisFactory.Models.ConfigEntities.UriComponentsList.Base
  type: Field
  source:
    remote:
      path: UrisFactory/UrisAutoGenerator/Models/ConfigEntities/UriComponentsList.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: Base
    path: Models/ConfigEntities/UriComponentsList.cs
    startLine: 8
  assemblies:
  - UrisFactory
  namespace: UrisFactory.Models.ConfigEntities
  syntax:
    content: public const string Base = "base"
    return:
      type: System.String
    content.vb: Public Const Base As String = "base"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: UrisFactory.Models.ConfigEntities.UriComponentsList.Character
  commentId: F:UrisFactory.Models.ConfigEntities.UriComponentsList.Character
  id: Character
  parent: UrisFactory.Models.ConfigEntities.UriComponentsList
  langs:
  - csharp
  - vb
  name: Character
  nameWithType: UriComponentsList.Character
  fullName: UrisFactory.Models.ConfigEntities.UriComponentsList.Character
  type: Field
  source:
    remote:
      path: UrisFactory/UrisAutoGenerator/Models/ConfigEntities/UriComponentsList.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: Character
    path: Models/ConfigEntities/UriComponentsList.cs
    startLine: 9
  assemblies:
  - UrisFactory
  namespace: UrisFactory.Models.ConfigEntities
  syntax:
    content: public const string Character = "character"
    return:
      type: System.String
    content.vb: Public Const Character As String = "character"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: UrisFactory.Models.ConfigEntities.UriComponentsList.ResourceClass
  commentId: F:UrisFactory.Models.ConfigEntities.UriComponentsList.ResourceClass
  id: ResourceClass
  parent: UrisFactory.Models.ConfigEntities.UriComponentsList
  langs:
  - csharp
  - vb
  name: ResourceClass
  nameWithType: UriComponentsList.ResourceClass
  fullName: UrisFactory.Models.ConfigEntities.UriComponentsList.ResourceClass
  type: Field
  source:
    remote:
      path: UrisFactory/UrisAutoGenerator/Models/ConfigEntities/UriComponentsList.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: ResourceClass
    path: Models/ConfigEntities/UriComponentsList.cs
    startLine: 10
  assemblies:
  - UrisFactory
  namespace: UrisFactory.Models.ConfigEntities
  syntax:
    content: public const string ResourceClass = "resourceClass"
    return:
      type: System.String
    content.vb: Public Const ResourceClass As String = "resourceClass"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: UrisFactory.Models.ConfigEntities.UriComponentsList.Identifier
  commentId: F:UrisFactory.Models.ConfigEntities.UriComponentsList.Identifier
  id: Identifier
  parent: UrisFactory.Models.ConfigEntities.UriComponentsList
  langs:
  - csharp
  - vb
  name: Identifier
  nameWithType: UriComponentsList.Identifier
  fullName: UrisFactory.Models.ConfigEntities.UriComponentsList.Identifier
  type: Field
  source:
    remote:
      path: UrisFactory/UrisAutoGenerator/Models/ConfigEntities/UriComponentsList.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: Identifier
    path: Models/ConfigEntities/UriComponentsList.cs
    startLine: 11
  assemblies:
  - UrisFactory
  namespace: UrisFactory.Models.ConfigEntities
  syntax:
    content: public const string Identifier = "identifier"
    return:
      type: System.String
    content.vb: Public Const Identifier As String = "identifier"
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: UrisFactory.Models.ConfigEntities.UriComponentsList.DefaultParameters
  commentId: P:UrisFactory.Models.ConfigEntities.UriComponentsList.DefaultParameters
  id: DefaultParameters
  parent: UrisFactory.Models.ConfigEntities.UriComponentsList
  langs:
  - csharp
  - vb
  name: DefaultParameters
  nameWithType: UriComponentsList.DefaultParameters
  fullName: UrisFactory.Models.ConfigEntities.UriComponentsList.DefaultParameters
  type: Property
  source:
    remote:
      path: UrisFactory/UrisAutoGenerator/Models/ConfigEntities/UriComponentsList.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: DefaultParameters
    path: Models/ConfigEntities/UriComponentsList.cs
    startLine: 15
  assemblies:
  - UrisFactory
  namespace: UrisFactory.Models.ConfigEntities
  syntax:
    content: public static ImmutableList<string> DefaultParameters { get; }
    parameters: []
    return:
      type: System.Collections.Immutable.ImmutableList{System.String}
    content.vb: Public Shared ReadOnly Property DefaultParameters As ImmutableList(Of String)
  overload: UrisFactory.Models.ConfigEntities.UriComponentsList.DefaultParameters*
  modifiers.csharp:
  - public
  - static
  - get
  modifiers.vb:
  - Public
  - Shared
  - ReadOnly
references:
- uid: UrisFactory.Models.ConfigEntities
  commentId: N:UrisFactory.Models.ConfigEntities
  name: UrisFactory.Models.ConfigEntities
  nameWithType: UrisFactory.Models.ConfigEntities
  fullName: UrisFactory.Models.ConfigEntities
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: UrisFactory.Models.ConfigEntities.UriComponentsList.DefaultParameters*
  commentId: Overload:UrisFactory.Models.ConfigEntities.UriComponentsList.DefaultParameters
  name: DefaultParameters
  nameWithType: UriComponentsList.DefaultParameters
  fullName: UrisFactory.Models.ConfigEntities.UriComponentsList.DefaultParameters
- uid: System.Collections.Immutable.ImmutableList{System.String}
  commentId: T:System.Collections.Immutable.ImmutableList{System.String}
  parent: System.Collections.Immutable
  definition: System.Collections.Immutable.ImmutableList`1
  name: ImmutableList<String>
  nameWithType: ImmutableList<String>
  fullName: System.Collections.Immutable.ImmutableList<System.String>
  nameWithType.vb: ImmutableList(Of String)
  fullName.vb: System.Collections.Immutable.ImmutableList(Of System.String)
  name.vb: ImmutableList(Of String)
  spec.csharp:
  - uid: System.Collections.Immutable.ImmutableList`1
    name: ImmutableList
    nameWithType: ImmutableList
    fullName: System.Collections.Immutable.ImmutableList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Immutable.ImmutableList`1
    name: ImmutableList
    nameWithType: ImmutableList
    fullName: System.Collections.Immutable.ImmutableList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.String
    name: String
    nameWithType: String
    fullName: System.String
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Immutable.ImmutableList`1
  commentId: T:System.Collections.Immutable.ImmutableList`1
  isExternal: true
  name: ImmutableList<T>
  nameWithType: ImmutableList<T>
  fullName: System.Collections.Immutable.ImmutableList<T>
  nameWithType.vb: ImmutableList(Of T)
  fullName.vb: System.Collections.Immutable.ImmutableList(Of T)
  name.vb: ImmutableList(Of T)
  spec.csharp:
  - uid: System.Collections.Immutable.ImmutableList`1
    name: ImmutableList
    nameWithType: ImmutableList
    fullName: System.Collections.Immutable.ImmutableList
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Collections.Immutable.ImmutableList`1
    name: ImmutableList
    nameWithType: ImmutableList
    fullName: System.Collections.Immutable.ImmutableList
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Collections.Immutable
  commentId: N:System.Collections.Immutable
  isExternal: true
  name: System.Collections.Immutable
  nameWithType: System.Collections.Immutable
  fullName: System.Collections.Immutable
