# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.MIKEL_PAT }} 
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Install Pellet reasoner
      working-directory: pellet
      run: mvn install
    - name: Launch tests
      run: mvn surefire-report:report -DontFile=roh/roh-v2.owl -DdataFile=roh/examples/data.ttl -Duneskos=roh/unesco-individuals.rdf
    - name: Generate documentation
      run: mvn javadoc:test-javadoc
    - name: Deploy github pages
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
         keep_files: true    
         publish_dir: target/site
         github_token: ${{ secrets.GITHUB_TOKEN }}
