[[entities]] # Publicaciones, documentos científicos y técnicos
code = "060.010.010.000"
ontology = "bibo"
class = "AcademicArticle"
id.resource = "Article"
id.format = "{doi}"

    [[entities.relations]]
    ontology = "roh"
    name = "correspondingAuthorOf"
    inverse_ontology = "roh"
    inverse_name = "correspondingAuthor"
    link_to_cvn_person = true

    [[entities.properties]]
    ontology = "roh"
    name = "title"
    format = "{title}"

        [[entities.properties.sources]]
        code = "060.010.010.030"
        name = "title"
        bean = "Value"

    [[entities.properties]]
    ontology = "vivo"
    name = "dateTime"
    format = "{publication_date}"

        [[entities.properties.sources]]
        code = "060.010.010.140"
        name = "publication_date"
        bean = "Value"

    [[entities.properties]]
    ontology = "bibo"
    name = "start"
    format = "{initialpage}"

        [[entities.properties.sources]]
        code = "060.010.010.090"
        name = "initialpage"
        bean = "InitialPage"

    [[entities.properties]]
    ontology = "bibo"
    name = "end"
    format = "{finalpage}"

        [[entities.properties.sources]]
        code = "060.010.010.090"
        name = "finalpage"
        bean = "FinalPage"

[[entities]]
code = "010.020.000.000"
ontology = "roh"
class = "Position"
id.fallback = "uuid4"

    [[entities.subentities]]
    ontology = "foaf"
    class = "Organization"

        [[entities.relations]]
        ontology = "vivo"
        name = "relates"
        inverse_ontology = "vivo"
        inverse_name = "relatedBy"

        [[entities.properties]]
        ontology = "foaf"
        name = "mame"
        format = "{name}"

            [[entities.properties.sources]]
            code = "010.020.000.020"
            name = "name"
            bean = "Value"

    [[entities.relations]]
    ontology = "roh"
    name = "hasPosition"
    inverse_ontology = "roh"
    inverse_name = "positionOf"
    link_to_cvn_person = true

    [[entities.properties]]
    ontology = "vivo"
    name = "HRJobTitle"
    format = "{title}"

        [[entities.properties.sources]]
        code = "010.020.000.170"
        name = "title"
        bean = "Value"

    [[entities.properties]]
    ontology = "vivo"
    name = "description"
    format = "{description}"

        [[entities.properties.sources]]
        code = "010.020.000.260"
        name = "description"
        bean = "Value"

[[entities]] # Formación académica recibida
code = "020.010.010.000"
ontology = "vivo"
class = "AcademicDegree"

    [[entities.criteria.property]]
    code = "020.010.010.010"
    values = ["950"]

    [[entities.properties]]
    ontology = "vivo"
    name = "dateTime"
    format = "{date}"

        [[entities.properties.sources]]
        code = "020.010.010.130"
        name = "date"
        bean = "Value"

    [[entities.properties]]
    ontology = "roh"
    name = "title"
    format = "{title}"

        [[entities.properties.sources]]
        code = "020.010.010.030"
        name = "title"
        bean = "Name"

[[entities]] # Doctorado
code = "020.010.020.000"
ontology = "roh"
class = "PhDThesis"

    [[entities.properties]]
    ontology = "vivo"
    name = "dateTime"
    format = "{date}"

        [[entities.properties.sources]]
        code = "020.010.020.140"
        name = "date"
        bean = "Value"

    [[entities.properties]]
    ontology = "roh"
    name = "title"
    format = "{title}"

        [[entities.properties.sources]]
        code = "020.010.020.160"
        name = "title"
        bean = "Value"

[[entities]] # Certificado de idiomas
code = "020.060.000.000"
ontology = "roh"
class = "LanguageCertificate"

    [[entities.relations]]
    ontology = "roh"
    name = "hasAccreditation"
    inverse_ontology = "roh"
    inverse_name = "accreditationOf"
    link_to_cvn_person = true

    [[entities.properties]]
    ontology = "roh"
    name = "readingSkill"
    format = "{skill}"

        [[entities.properties.sources]]
        code = "020.060.000.130"
        name = "skill"
        bean = "Value"

    [[entities.properties]]
    ontology = "roh"
    name = "spokenInteractionSkill"
    format = "{skill}"

        [[entities.properties.sources]]
        code = "020.060.000.140"
        name = "skill"
        bean = "Value"

    [[entities.properties]]
    ontology = "roh"
    name = "speakingSkill"
    format = "{skill}"

        [[entities.properties.sources]]
        code = "020.060.000.150"
        name = "skill"
        bean = "Value"

    [[entities.properties]]
    ontology = "roh"
    name = "writingSkill"
    format = "{skill}"

        [[entities.properties.sources]]
        code = "020.060.000.160"
        name = "skill"
        bean = "Value"