[[entities]] # Publicaciones, documentos científicos y técnicos
code = "060.010.010.000"
ontology = "bibo"
class = "AcademicArticle"
id.resource = "Article"
id.format = "{doi}"

    [[entities.properties]]
    ontology = "roh"
    name = "title"
    format = "{title}"

        [[entities.properties.sources]]
        code = "060.010.010.030"
        name = "title"
        bean = "Value"

    [[entities.properties]]
    ontology = "xsd"
    name = "dateTime"
    format = "{publication_date}"

        [[entities.properties.sources]]
        code = "060.010.010.140"
        name = "publication_date"
        bean = "Value"

[[entities]]
code = "010.020.000.000"
ontology = "roh"
class = "Position"
id.fallback = "uuid4"

    [[entities.properties]]
    ontology = "vivo"
    name = "HRJobTitle"
    format = "{title}"

        [[entities.properties.sources]]
        code = "010.020.000.170"
        name = "title"
        bean = "Value"

    [[entities.properties]]
    ontology = "vivo"
    name = "description"
    format = "{description}"

        [[entities.properties.sources]]
        code = "010.020.000.260"
        name = "description"
        bean = "Value"