[[entities]] # Publicaciones, documentos científicos y técnicos
code = "060.010.010.000"
ontology = "bibo"
classname = "AcademicArticle"
id.resource = "Article"
id.format = "{doi}"

    [[entities.relationships]]
    ontology = "roh"
    name = "correspondingAuthor"
    inverse_ontology = "roh"
    inverse_name = "correspondingAuthorOf"
    link_to_cvn_person = true

    [[entities.properties]]
    ontology = "roh"
    name = "title"
    format = "{title}"

        [[entities.properties.sources]]
        code = "060.010.010.030"
        name = "title"
        bean = "Value"

    [[entities.properties]]
    ontology = "vivo"
    name = "dateTime"
    format = "{publication_date}"

        [[entities.properties.sources]]
        code = "060.010.010.140"
        name = "publication_date"
        bean = "Value"

    [[entities.properties]]
    ontology = "bibo"
    name = "start"
    format = "{initialpage}"

        [[entities.properties.sources]]
        code = "060.010.010.090"
        name = "initialpage"
        bean = "InitialPage"

    [[entities.properties]]
    ontology = "bibo"
    name = "end"
    format = "{finalpage}"

        [[entities.properties.sources]]
        code = "060.010.010.090"
        name = "finalpage"
        bean = "FinalPage"

[[entities]]
code = "010.020.000.000"
ontology = "roh"
classname = "Position"
id.fallback = "uuid4"

    [[entities.subentities]]
    ontology = "vivo"
    classname = "DateTimeInterval"

        [[entities.subentities.relationships]]
        inverse_ontology = "vivo"
        inverse_name = "dateTimeInterval"

        [[entities.subentities.subentities]]
        ontology = "vivo"
        classname = "DateTimeValue"

            [[entities.subentities.subentities.relationships]]
            inverse_ontology = "vivo"
            inverse_name = "start"

            [[entities.subentities.subentities.properties]]
            ontology = "vivo"
            name = "start"
            format = "{start}"

                [[entities.subentities.subentities.properties.sources]]
                code = "010.020.000.180"
                name = "start"
                bean = "Value"

        [[entities.subentities.subentities]]
        ontology = "vivo"
        classname = "DateTimeValue"

            [[entities.subentities.subentities.relationships]]
            inverse_ontology = "vivo"
            inverse_name = "end"

            [[entities.subentities.subentities.properties]]
            ontology = "vivo"
            name = "end"
            format = "{end}"

                [[entities.subentities.subentities.properties.sources]]
                code = "010.020.000.310"
                name = "end"
                bean = "Value"

    [[entities.subentities]]
    ontology = "foaf"
    classname = "Organization"

        [[entities.subentities.relationships]]
        ontology = "vivo"
        name = "relates"
        inverse_ontology = "vivo"
        inverse_name = "relatedBy"

        [[entities.subentities.properties]]
        ontology = "foaf"
        name = "name"
        format = "{name}"

            [[entities.subentities.properties.sources]]
            code = "010.020.000.020"
            name = "name"
            bean = "Name"

    [[entities.relationships]]
    ontology = "roh"
    name = "hasPosition"
    inverse_ontology = "roh"
    inverse_name = "positionOf"
    link_to_cvn_person = true

    [[entities.properties]]
    ontology = "vivo"
    name = "HRJobTitle"
    format = "{title}"

        [[entities.properties.sources]]
        code = "010.020.000.170"
        name = "title"
        bean = "Value"

    [[entities.properties]]
    ontology = "vivo"
    name = "description"
    format = "{description}"

        [[entities.properties.sources]]
        code = "010.020.000.260"
        name = "description"
        bean = "Value"

[[entities]] # Formación académica recibida
code = "020.010.010.000"
ontology = "vivo"
classname = "AwardedDegree"

    [[entities.criteria.property]]
    ontology = "vivo"
    name = "relates"
    inverse_ontology = "vivo"
    inverse_name = "relates"
    link_to_cvn_person = true

    [[entities.properties]]
    ontology = "vivo"
    name = "dateTime"
    format = "{date}"

        [[entities.properties.sources]]
        code = "020.010.010.130"
        name = "date"
        bean = "Value"

    [[entities.subentities]]
    ontology = "vivo"
    classname = "AcademicDegree"

        [[entities.subentities.relationships]]
        ontology = "vivo"
        name = "relates"

        [[entities.subentities.properties]]
        ontology = "roh"
        name = "title"
        format = "{title}"

            [[entities.subentities.properties.sources]]
            code = "020.010.010.030"
            name = "title"
            bean = "Name"

        [[entities.subentities.subentities]]
        ontology = "vivo"
        classname = "University"

            [[entities.subentities.subentities.relationships]]
            ontology = "roh"
            name = "awards"
            inverse_ontology = "roh"
            inverse_name = "awardedBy"

            [[entities.subentities.subentities.properties]]
            ontology = "foaf"
            name = "name"
            format = "{title}"

                [[entities.subentities.subentities.properties.sources]]
                code = "020.010.010.090"
                name = "name"
                bean = "Name"

[[entities]] # Doctorado
code = "020.010.020.000"
ontology = "roh"
classname = "PhDThesis"

    [[entities.properties]]
    ontology = "vivo"
    name = "dateTime"
    format = "{date}"

        [[entities.properties.sources]]
        code = "020.010.020.140"
        name = "date"
        bean = "Value"

    [[entities.properties]]
    ontology = "roh"
    name = "title"
    format = "{title}"

        [[entities.properties.sources]]
        code = "020.010.020.160"
        name = "title"
        bean = "Value"

[[entities]] # Certificado de idiomas
code = "020.060.000.000"
ontology = "roh"
classname = "LanguageCertificate"

    [[entities.relationships]]
    ontology = "roh"
    name = "hasAccreditation"
    inverse_ontology = "roh"
    inverse_name = "accreditationOf"
    link_to_cvn_person = true

    [[entities.properties]]
    ontology = "roh"
    name = "language"
    format = "{language}"

        [[entities.properties.sources]]
        code = "020.060.000.010"
        name = "language"
        bean = "Identification"

    [[entities.properties]]
    ontology = "roh"
    name = "readingSkill"
    format = "{skill}"

        [[entities.properties.sources]]
        code = "020.060.000.130"
        name = "skill"
        bean = "Value"

    [[entities.properties]]
    ontology = "roh"
    name = "spokenInteractionSkill"
    format = "{skill}"

        [[entities.properties.sources]]
        code = "020.060.000.140"
        name = "skill"
        bean = "Value"

    [[entities.properties]]
    ontology = "roh"
    name = "speakingSkill"
    format = "{skill}"

        [[entities.properties.sources]]
        code = "020.060.000.150"
        name = "skill"
        bean = "Value"

    [[entities.properties]]
    ontology = "roh"
    name = "writingSkill"
    format = "{skill}"

        [[entities.properties.sources]]
        code = "020.060.000.160"
        name = "skill"
        bean = "Value"