[config]
version = "1"

[[codes]] # Identificación CVN
id = "000.010.000.000"

    [[codes.instance]]
    ontology = "foaf"
    class = "Person"
    id = "cvn_owner"

    [[codes.subcodes]] # Apellidos
    id = "000.010.000.010"

        [[codes.subcodes.variable]] # 1er apellido
        beanName = "FirstFamilyName"
        variableName = "cvn_owner_first_family_name"

        [[codes.subcodes.variable]] # 2o apellido
        beanName = "SecondFamilyName"
        variableName = "cvn_owner_second_family_name"

    [[codes.subcodes]] # Nombre
    id = "000.010.000.010"

        [[codes.subcodes.variable]] # 1er apellido
        # Se asume que el Bean por defecto es {...}Value
        variableName = "cvn_owner_first_name"

    [[codes.property]] # Juntar nombre y apellidos en una única propiedad
    instance = "cvn_owner"
    ontology = "foaf"
    name = "name"

        [[codes.property.value]] # Concatenar nombre, apellidos
        type = "concatenate"
        values = ["$cvn_owner_first_name", " ", "$cvn_owner_first_family_name", " ", "cvn_owner_second_family_name"]

    [[codes.subcodes]] # Email
    id = "000.010.000.010"

[[codes]] # AcademicArticle
id = "060.010.010.000"

    [[codes.instance]]
    ontology = "roh"
    class = "AcademicArticle"
    id = ""
