[[ontologies]]
shortname = "roh"
uri_base = "https://purl.org/roh/"
primary = true

[[ontologies]]
shortname = "bibo"
uri_base = "http://purl.org/ontology/bibo/"

[[ontologies]]
shortname = "vivo"
uri_base = "http://vivoweb.org/ontology/core#"

[[ontologies]]
shortname = "foaf"
uri_base = "http://xmlns.com/foaf/0.1/"
