openapi: 3.0.0
info:
  title: Servicio conversión CVN-ROH
  description: Servidor HTTP que ofrece una API para convertir XML CVN a tripletas
    ROH.
  version: af0908b
servers:
- url: http://localhost:5000/v1
paths:
  /convert:
    post:
      summary: Convierte CVN XML a tripletas ROH
      operationId: convert_post
      parameters:
      - name: orcid
        in: query
        description: ORCID de la persona del CVN a convertir
        required: true
        style: form
        explode: true
        schema:
          type: string
      - name: format
        in: query
        description: Formato de salida deseado
        required: false
        style: form
        explode: true
        schema:
          type: string
          default: xml
          enum:
          - xml
          - n3
          - turtle
          - nt
          - pretty-xml
          - trix
          - trig
          - nquads
      requestBody:
        content:
          application/x-www-form-urlencoded:
            schema:
              type: string
              format: binary
        required: true
      responses:
        "200":
          description: Resultado de la conversión, en el formato que se haya pedido
            (xml por defecto)
        "422":
          description: Error de validación. Algún campo no se está incluyendo o se
            está incluyendo mal. Ver mensaje de respuesta
        "500":
          description: Error de conversión (archivo demasiado grande/mal formateado)
            o del servidor en general.
      x-openapi-router-controller: swagger_server.controllers.default_controller
components: {}

