### YamlMime:ManagedReference
items:
- uid: CronConfigure.Models.Enumeracion.JobType
  commentId: T:CronConfigure.Models.Enumeracion.JobType
  id: JobType
  parent: CronConfigure.Models.Enumeracion
  children:
  - CronConfigure.Models.Enumeracion.JobType.All
  - CronConfigure.Models.Enumeracion.JobType.Failed
  - CronConfigure.Models.Enumeracion.JobType.Succeeded
  langs:
  - csharp
  - vb
  name: JobType
  nameWithType: JobType
  fullName: CronConfigure.Models.Enumeracion.JobType
  type: Enum
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Enumeracion/JobType.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: JobType
    path: Models/Enumeracion/JobType.cs
    startLine: 7
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Enumeracion
  syntax:
    content: public enum JobType
    content.vb: Public Enum JobType
  modifiers.csharp:
  - public
  - enum
  modifiers.vb:
  - Public
  - Enum
- uid: CronConfigure.Models.Enumeracion.JobType.All
  commentId: F:CronConfigure.Models.Enumeracion.JobType.All
  id: All
  parent: CronConfigure.Models.Enumeracion.JobType
  langs:
  - csharp
  - vb
  name: All
  nameWithType: JobType.All
  fullName: CronConfigure.Models.Enumeracion.JobType.All
  type: Field
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Enumeracion/JobType.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: All
    path: Models/Enumeracion/JobType.cs
    startLine: 9
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Enumeracion
  syntax:
    content: All = 0
    return:
      type: CronConfigure.Models.Enumeracion.JobType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: CronConfigure.Models.Enumeracion.JobType.Failed
  commentId: F:CronConfigure.Models.Enumeracion.JobType.Failed
  id: Failed
  parent: CronConfigure.Models.Enumeracion.JobType
  langs:
  - csharp
  - vb
  name: Failed
  nameWithType: JobType.Failed
  fullName: CronConfigure.Models.Enumeracion.JobType.Failed
  type: Field
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Enumeracion/JobType.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: Failed
    path: Models/Enumeracion/JobType.cs
    startLine: 10
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Enumeracion
  syntax:
    content: Failed = 1
    return:
      type: CronConfigure.Models.Enumeracion.JobType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
- uid: CronConfigure.Models.Enumeracion.JobType.Succeeded
  commentId: F:CronConfigure.Models.Enumeracion.JobType.Succeeded
  id: Succeeded
  parent: CronConfigure.Models.Enumeracion.JobType
  langs:
  - csharp
  - vb
  name: Succeeded
  nameWithType: JobType.Succeeded
  fullName: CronConfigure.Models.Enumeracion.JobType.Succeeded
  type: Field
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Enumeracion/JobType.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: Succeeded
    path: Models/Enumeracion/JobType.cs
    startLine: 11
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Enumeracion
  syntax:
    content: Succeeded = 2
    return:
      type: CronConfigure.Models.Enumeracion.JobType
  modifiers.csharp:
  - public
  - const
  modifiers.vb:
  - Public
  - Const
references:
- uid: CronConfigure.Models.Enumeracion
  commentId: N:CronConfigure.Models.Enumeracion
  name: CronConfigure.Models.Enumeracion
  nameWithType: CronConfigure.Models.Enumeracion
  fullName: CronConfigure.Models.Enumeracion
- uid: CronConfigure.Models.Enumeracion.JobType
  commentId: T:CronConfigure.Models.Enumeracion.JobType
  parent: CronConfigure.Models.Enumeracion
  name: JobType
  nameWithType: JobType
  fullName: CronConfigure.Models.Enumeracion.JobType
