### YamlMime:ManagedReference
items:
- uid: CronConfigure.Filters
  commentId: N:CronConfigure.Filters
  id: CronConfigure.Filters
  children:
  - CronConfigure.Filters.EnumSchemaFilter
  - CronConfigure.Filters.HangfireDashboardNoAuthorizationFilter
  - CronConfigure.Filters.ProlongExpirationTimeAttribute
  langs:
  - csharp
  - vb
  name: CronConfigure.Filters
  nameWithType: CronConfigure.Filters
  fullName: CronConfigure.Filters
  type: Namespace
  assemblies:
  - CronConfigure
references:
- uid: CronConfigure.Filters.EnumSchemaFilter
  commentId: T:CronConfigure.Filters.EnumSchemaFilter
  name: EnumSchemaFilter
  nameWithType: EnumSchemaFilter
  fullName: CronConfigure.Filters.EnumSchemaFilter
- uid: CronConfigure.Filters.HangfireDashboardNoAuthorizationFilter
  commentId: T:CronConfigure.Filters.HangfireDashboardNoAuthorizationFilter
  name: HangfireDashboardNoAuthorizationFilter
  nameWithType: HangfireDashboardNoAuthorizationFilter
  fullName: CronConfigure.Filters.HangfireDashboardNoAuthorizationFilter
- uid: CronConfigure.Filters.ProlongExpirationTimeAttribute
  commentId: T:CronConfigure.Filters.ProlongExpirationTimeAttribute
  name: ProlongExpirationTimeAttribute
  nameWithType: ProlongExpirationTimeAttribute
  fullName: CronConfigure.Filters.ProlongExpirationTimeAttribute
