### YamlMime:ManagedReference
items:
- uid: CronConfigure.Models.Hangfire
  commentId: N:CronConfigure.Models.Hangfire
  id: CronConfigure.Models.Hangfire
  children:
  - CronConfigure.Models.Hangfire.AggregatedCounter
  - CronConfigure.Models.Hangfire.Count
  - CronConfigure.Models.Hangfire.Counter
  - CronConfigure.Models.Hangfire.Hash
  - CronConfigure.Models.Hangfire.Job
  - CronConfigure.Models.Hangfire.JobParameter
  - CronConfigure.Models.Hangfire.JobQueue
  - CronConfigure.Models.Hangfire.List
  - CronConfigure.Models.Hangfire.Schema
  - CronConfigure.Models.Hangfire.Server
  - CronConfigure.Models.Hangfire.Set
  - CronConfigure.Models.Hangfire.State
  langs:
  - csharp
  - vb
  name: CronConfigure.Models.Hangfire
  nameWithType: CronConfigure.Models.Hangfire
  fullName: CronConfigure.Models.Hangfire
  type: Namespace
  assemblies:
  - CronConfigure
references:
- uid: CronConfigure.Models.Hangfire.AggregatedCounter
  commentId: T:CronConfigure.Models.Hangfire.AggregatedCounter
  name: AggregatedCounter
  nameWithType: AggregatedCounter
  fullName: CronConfigure.Models.Hangfire.AggregatedCounter
- uid: CronConfigure.Models.Hangfire.Count
  commentId: T:CronConfigure.Models.Hangfire.Count
  name: Count
  nameWithType: Count
  fullName: CronConfigure.Models.Hangfire.Count
- uid: CronConfigure.Models.Hangfire.Counter
  commentId: T:CronConfigure.Models.Hangfire.Counter
  name: Counter
  nameWithType: Counter
  fullName: CronConfigure.Models.Hangfire.Counter
- uid: CronConfigure.Models.Hangfire.Hash
  commentId: T:CronConfigure.Models.Hangfire.Hash
  name: Hash
  nameWithType: Hash
  fullName: CronConfigure.Models.Hangfire.Hash
- uid: CronConfigure.Models.Hangfire.Job
  commentId: T:CronConfigure.Models.Hangfire.Job
  parent: CronConfigure.Models.Hangfire
  name: Job
  nameWithType: Job
  fullName: CronConfigure.Models.Hangfire.Job
- uid: CronConfigure.Models.Hangfire.JobParameter
  commentId: T:CronConfigure.Models.Hangfire.JobParameter
  name: JobParameter
  nameWithType: JobParameter
  fullName: CronConfigure.Models.Hangfire.JobParameter
- uid: CronConfigure.Models.Hangfire.JobQueue
  commentId: T:CronConfigure.Models.Hangfire.JobQueue
  name: JobQueue
  nameWithType: JobQueue
  fullName: CronConfigure.Models.Hangfire.JobQueue
- uid: CronConfigure.Models.Hangfire.List
  commentId: T:CronConfigure.Models.Hangfire.List
  name: List
  nameWithType: List
  fullName: CronConfigure.Models.Hangfire.List
- uid: CronConfigure.Models.Hangfire.Schema
  commentId: T:CronConfigure.Models.Hangfire.Schema
  name: Schema
  nameWithType: Schema
  fullName: CronConfigure.Models.Hangfire.Schema
- uid: CronConfigure.Models.Hangfire.Server
  commentId: T:CronConfigure.Models.Hangfire.Server
  name: Server
  nameWithType: Server
  fullName: CronConfigure.Models.Hangfire.Server
- uid: CronConfigure.Models.Hangfire.Set
  commentId: T:CronConfigure.Models.Hangfire.Set
  name: Set
  nameWithType: Set
  fullName: CronConfigure.Models.Hangfire.Set
- uid: CronConfigure.Models.Hangfire.State
  commentId: T:CronConfigure.Models.Hangfire.State
  name: State
  nameWithType: State
  fullName: CronConfigure.Models.Hangfire.State
- uid: CronConfigure.Models.Hangfire
  commentId: N:CronConfigure.Models.Hangfire
  name: CronConfigure.Models.Hangfire
  nameWithType: CronConfigure.Models.Hangfire
  fullName: CronConfigure.Models.Hangfire
