### YamlMime:ManagedReference
items:
- uid: CronConfigure.Models.Enumeracion
  commentId: N:CronConfigure.Models.Enumeracion
  id: CronConfigure.Models.Enumeracion
  children:
  - CronConfigure.Models.Enumeracion.JobType
  langs:
  - csharp
  - vb
  name: CronConfigure.Models.Enumeracion
  nameWithType: CronConfigure.Models.Enumeracion
  fullName: CronConfigure.Models.Enumeracion
  type: Namespace
  assemblies:
  - CronConfigure
references:
- uid: CronConfigure.Models.Enumeracion.JobType
  commentId: T:CronConfigure.Models.Enumeracion.JobType
  parent: CronConfigure.Models.Enumeracion
  name: JobType
  nameWithType: JobType
  fullName: CronConfigure.Models.Enumeracion.JobType
- uid: CronConfigure.Models.Enumeracion
  commentId: N:CronConfigure.Models.Enumeracion
  name: CronConfigure.Models.Enumeracion
  nameWithType: CronConfigure.Models.Enumeracion
  fullName: CronConfigure.Models.Enumeracion
