### YamlMime:ManagedReference
items:
- uid: CronConfigure.Models.Services.IProgramingMethodService
  commentId: T:CronConfigure.Models.Services.IProgramingMethodService
  id: IProgramingMethodService
  parent: CronConfigure.Models.Services
  children:
  - CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryJob(System.Guid,System.DateTime,System.Nullable{System.DateTime},System.String,System.String)
  - CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryRecurringJob(System.Guid,System.String,System.String,System.DateTime,System.Nullable{System.DateTime},System.String,System.String)
  - CronConfigure.Models.Services.IProgramingMethodService.ProgramRecurringJob(System.Guid,System.String,System.String,System.Nullable{System.DateTime},System.String,System.String)
  - CronConfigure.Models.Services.IProgramingMethodService.PublishRepositories(System.Guid,System.Nullable{System.DateTime},System.String,System.String)
  langs:
  - csharp
  - vb
  name: IProgramingMethodService
  nameWithType: IProgramingMethodService
  fullName: CronConfigure.Models.Services.IProgramingMethodService
  type: Interface
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Services/IProgramingMethodService.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: IProgramingMethodService
    path: Models/Services/IProgramingMethodService.cs
    startLine: 7
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Services
  syntax:
    content: public interface IProgramingMethodService
    content.vb: Public Interface IProgramingMethodService
  modifiers.csharp:
  - public
  - interface
  modifiers.vb:
  - Public
  - Interface
- uid: CronConfigure.Models.Services.IProgramingMethodService.PublishRepositories(System.Guid,System.Nullable{System.DateTime},System.String,System.String)
  commentId: M:CronConfigure.Models.Services.IProgramingMethodService.PublishRepositories(System.Guid,System.Nullable{System.DateTime},System.String,System.String)
  id: PublishRepositories(System.Guid,System.Nullable{System.DateTime},System.String,System.String)
  parent: CronConfigure.Models.Services.IProgramingMethodService
  langs:
  - csharp
  - vb
  name: PublishRepositories(Guid, Nullable<DateTime>, String, String)
  nameWithType: IProgramingMethodService.PublishRepositories(Guid, Nullable<DateTime>, String, String)
  fullName: CronConfigure.Models.Services.IProgramingMethodService.PublishRepositories(System.Guid, System.Nullable<System.DateTime>, System.String, System.String)
  type: Method
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Services/IProgramingMethodService.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: PublishRepositories
    path: Models/Services/IProgramingMethodService.cs
    startLine: 9
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Services
  syntax:
    content: string PublishRepositories(Guid idRepositoryGuid, DateTime? fecha = default(DateTime? ), string pSet = null, string codigoObjeto = null)
    parameters:
    - id: idRepositoryGuid
      type: System.Guid
    - id: fecha
      type: System.Nullable{System.DateTime}
    - id: pSet
      type: System.String
    - id: codigoObjeto
      type: System.String
    return:
      type: System.String
    content.vb: Function PublishRepositories(idRepositoryGuid As Guid, fecha As Date? = Nothing, pSet As String = Nothing, codigoObjeto As String = Nothing) As String
  overload: CronConfigure.Models.Services.IProgramingMethodService.PublishRepositories*
  nameWithType.vb: IProgramingMethodService.PublishRepositories(Guid, Nullable(Of DateTime), String, String)
  fullName.vb: CronConfigure.Models.Services.IProgramingMethodService.PublishRepositories(System.Guid, System.Nullable(Of System.DateTime), System.String, System.String)
  name.vb: PublishRepositories(Guid, Nullable(Of DateTime), String, String)
- uid: CronConfigure.Models.Services.IProgramingMethodService.ProgramRecurringJob(System.Guid,System.String,System.String,System.Nullable{System.DateTime},System.String,System.String)
  commentId: M:CronConfigure.Models.Services.IProgramingMethodService.ProgramRecurringJob(System.Guid,System.String,System.String,System.Nullable{System.DateTime},System.String,System.String)
  id: ProgramRecurringJob(System.Guid,System.String,System.String,System.Nullable{System.DateTime},System.String,System.String)
  parent: CronConfigure.Models.Services.IProgramingMethodService
  langs:
  - csharp
  - vb
  name: ProgramRecurringJob(Guid, String, String, Nullable<DateTime>, String, String)
  nameWithType: IProgramingMethodService.ProgramRecurringJob(Guid, String, String, Nullable<DateTime>, String, String)
  fullName: CronConfigure.Models.Services.IProgramingMethodService.ProgramRecurringJob(System.Guid, System.String, System.String, System.Nullable<System.DateTime>, System.String, System.String)
  type: Method
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Services/IProgramingMethodService.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: ProgramRecurringJob
    path: Models/Services/IProgramingMethodService.cs
    startLine: 10
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Services
  syntax:
    content: static void ProgramRecurringJob(Guid idRepository, string nombreCron, string cronExpression, DateTime? fecha = default(DateTime? ), string set = null, string codigoObjeto = null)
    parameters:
    - id: idRepository
      type: System.Guid
    - id: nombreCron
      type: System.String
    - id: cronExpression
      type: System.String
    - id: fecha
      type: System.Nullable{System.DateTime}
    - id: set
      type: System.String
    - id: codigoObjeto
      type: System.String
    content.vb: Shared Sub ProgramRecurringJob(idRepository As Guid, nombreCron As String, cronExpression As String, fecha As Date? = Nothing, set As String = Nothing, codigoObjeto As String = Nothing)
  overload: CronConfigure.Models.Services.IProgramingMethodService.ProgramRecurringJob*
  nameWithType.vb: IProgramingMethodService.ProgramRecurringJob(Guid, String, String, Nullable(Of DateTime), String, String)
  fullName.vb: CronConfigure.Models.Services.IProgramingMethodService.ProgramRecurringJob(System.Guid, System.String, System.String, System.Nullable(Of System.DateTime), System.String, System.String)
  name.vb: ProgramRecurringJob(Guid, String, String, Nullable(Of DateTime), String, String)
- uid: CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryJob(System.Guid,System.DateTime,System.Nullable{System.DateTime},System.String,System.String)
  commentId: M:CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryJob(System.Guid,System.DateTime,System.Nullable{System.DateTime},System.String,System.String)
  id: ProgramPublishRepositoryJob(System.Guid,System.DateTime,System.Nullable{System.DateTime},System.String,System.String)
  parent: CronConfigure.Models.Services.IProgramingMethodService
  langs:
  - csharp
  - vb
  name: ProgramPublishRepositoryJob(Guid, DateTime, Nullable<DateTime>, String, String)
  nameWithType: IProgramingMethodService.ProgramPublishRepositoryJob(Guid, DateTime, Nullable<DateTime>, String, String)
  fullName: CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryJob(System.Guid, System.DateTime, System.Nullable<System.DateTime>, System.String, System.String)
  type: Method
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Services/IProgramingMethodService.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: ProgramPublishRepositoryJob
    path: Models/Services/IProgramingMethodService.cs
    startLine: 11
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Services
  syntax:
    content: string ProgramPublishRepositoryJob(Guid idRepository, DateTime fechaInicio, DateTime? fecha = default(DateTime? ), string set = null, string codigoObjeto = null)
    parameters:
    - id: idRepository
      type: System.Guid
    - id: fechaInicio
      type: System.DateTime
    - id: fecha
      type: System.Nullable{System.DateTime}
    - id: set
      type: System.String
    - id: codigoObjeto
      type: System.String
    return:
      type: System.String
    content.vb: Function ProgramPublishRepositoryJob(idRepository As Guid, fechaInicio As Date, fecha As Date? = Nothing, set As String = Nothing, codigoObjeto As String = Nothing) As String
  overload: CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryJob*
  nameWithType.vb: IProgramingMethodService.ProgramPublishRepositoryJob(Guid, DateTime, Nullable(Of DateTime), String, String)
  fullName.vb: CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryJob(System.Guid, System.DateTime, System.Nullable(Of System.DateTime), System.String, System.String)
  name.vb: ProgramPublishRepositoryJob(Guid, DateTime, Nullable(Of DateTime), String, String)
- uid: CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryRecurringJob(System.Guid,System.String,System.String,System.DateTime,System.Nullable{System.DateTime},System.String,System.String)
  commentId: M:CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryRecurringJob(System.Guid,System.String,System.String,System.DateTime,System.Nullable{System.DateTime},System.String,System.String)
  id: ProgramPublishRepositoryRecurringJob(System.Guid,System.String,System.String,System.DateTime,System.Nullable{System.DateTime},System.String,System.String)
  parent: CronConfigure.Models.Services.IProgramingMethodService
  langs:
  - csharp
  - vb
  name: ProgramPublishRepositoryRecurringJob(Guid, String, String, DateTime, Nullable<DateTime>, String, String)
  nameWithType: IProgramingMethodService.ProgramPublishRepositoryRecurringJob(Guid, String, String, DateTime, Nullable<DateTime>, String, String)
  fullName: CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryRecurringJob(System.Guid, System.String, System.String, System.DateTime, System.Nullable<System.DateTime>, System.String, System.String)
  type: Method
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Services/IProgramingMethodService.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: ProgramPublishRepositoryRecurringJob
    path: Models/Services/IProgramingMethodService.cs
    startLine: 12
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Services
  syntax:
    content: void ProgramPublishRepositoryRecurringJob(Guid idRepository, string nombreCron, string cronExpression, DateTime fechaInicio, DateTime? fecha = default(DateTime? ), string set = null, string codigoObjeto = null)
    parameters:
    - id: idRepository
      type: System.Guid
    - id: nombreCron
      type: System.String
    - id: cronExpression
      type: System.String
    - id: fechaInicio
      type: System.DateTime
    - id: fecha
      type: System.Nullable{System.DateTime}
    - id: set
      type: System.String
    - id: codigoObjeto
      type: System.String
    content.vb: Sub ProgramPublishRepositoryRecurringJob(idRepository As Guid, nombreCron As String, cronExpression As String, fechaInicio As Date, fecha As Date? = Nothing, set As String = Nothing, codigoObjeto As String = Nothing)
  overload: CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryRecurringJob*
  nameWithType.vb: IProgramingMethodService.ProgramPublishRepositoryRecurringJob(Guid, String, String, DateTime, Nullable(Of DateTime), String, String)
  fullName.vb: CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryRecurringJob(System.Guid, System.String, System.String, System.DateTime, System.Nullable(Of System.DateTime), System.String, System.String)
  name.vb: ProgramPublishRepositoryRecurringJob(Guid, String, String, DateTime, Nullable(Of DateTime), String, String)
references:
- uid: CronConfigure.Models.Services
  commentId: N:CronConfigure.Models.Services
  name: CronConfigure.Models.Services
  nameWithType: CronConfigure.Models.Services
  fullName: CronConfigure.Models.Services
- uid: CronConfigure.Models.Services.IProgramingMethodService.PublishRepositories*
  commentId: Overload:CronConfigure.Models.Services.IProgramingMethodService.PublishRepositories
  name: PublishRepositories
  nameWithType: IProgramingMethodService.PublishRepositories
  fullName: CronConfigure.Models.Services.IProgramingMethodService.PublishRepositories
- uid: System.Guid
  commentId: T:System.Guid
  parent: System
  isExternal: true
  name: Guid
  nameWithType: Guid
  fullName: System.Guid
- uid: System.Nullable{System.DateTime}
  commentId: T:System.Nullable{System.DateTime}
  parent: System
  definition: System.Nullable`1
  name: Nullable<DateTime>
  nameWithType: Nullable<DateTime>
  fullName: System.Nullable<System.DateTime>
  nameWithType.vb: Nullable(Of DateTime)
  fullName.vb: System.Nullable(Of System.DateTime)
  name.vb: Nullable(Of DateTime)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.DateTime
    name: DateTime
    nameWithType: DateTime
    fullName: System.DateTime
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.DateTime
    name: DateTime
    nameWithType: DateTime
    fullName: System.DateTime
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
- uid: CronConfigure.Models.Services.IProgramingMethodService.ProgramRecurringJob*
  commentId: Overload:CronConfigure.Models.Services.IProgramingMethodService.ProgramRecurringJob
  name: ProgramRecurringJob
  nameWithType: IProgramingMethodService.ProgramRecurringJob
  fullName: CronConfigure.Models.Services.IProgramingMethodService.ProgramRecurringJob
- uid: CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryJob*
  commentId: Overload:CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryJob
  name: ProgramPublishRepositoryJob
  nameWithType: IProgramingMethodService.ProgramPublishRepositoryJob
  fullName: CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryJob
- uid: System.DateTime
  commentId: T:System.DateTime
  parent: System
  isExternal: true
  name: DateTime
  nameWithType: DateTime
  fullName: System.DateTime
- uid: CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryRecurringJob*
  commentId: Overload:CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryRecurringJob
  name: ProgramPublishRepositoryRecurringJob
  nameWithType: IProgramingMethodService.ProgramPublishRepositoryRecurringJob
  fullName: CronConfigure.Models.Services.IProgramingMethodService.ProgramPublishRepositoryRecurringJob
