### YamlMime:ManagedReference
items:
- uid: CronConfigure.Models.Recurrent
  commentId: T:CronConfigure.Models.Recurrent
  id: Recurrent
  parent: CronConfigure.Models
  children:
  - CronConfigure.Models.Recurrent.#ctor(CronConfigure.Models.Enumeracion.JobType,System.Int32)
  - CronConfigure.Models.Recurrent.DateType
  - CronConfigure.Models.Recurrent.Interval
  langs:
  - csharp
  - vb
  name: Recurrent
  nameWithType: Recurrent
  fullName: CronConfigure.Models.Recurrent
  type: Class
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Recurrent.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: Recurrent
    path: Models/Recurrent.cs
    startLine: 8
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models
  syntax:
    content: public class Recurrent
    content.vb: Public Class Recurrent
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CronConfigure.Models.Recurrent.DateType
  commentId: P:CronConfigure.Models.Recurrent.DateType
  id: DateType
  parent: CronConfigure.Models.Recurrent
  langs:
  - csharp
  - vb
  name: DateType
  nameWithType: Recurrent.DateType
  fullName: CronConfigure.Models.Recurrent.DateType
  type: Property
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Recurrent.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: DateType
    path: Models/Recurrent.cs
    startLine: 10
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models
  syntax:
    content: public JobType DateType { get; set; }
    parameters: []
    return:
      type: CronConfigure.Models.Enumeracion.JobType
    content.vb: Public Property DateType As JobType
  overload: CronConfigure.Models.Recurrent.DateType*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CronConfigure.Models.Recurrent.Interval
  commentId: P:CronConfigure.Models.Recurrent.Interval
  id: Interval
  parent: CronConfigure.Models.Recurrent
  langs:
  - csharp
  - vb
  name: Interval
  nameWithType: Recurrent.Interval
  fullName: CronConfigure.Models.Recurrent.Interval
  type: Property
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Recurrent.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: Interval
    path: Models/Recurrent.cs
    startLine: 12
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models
  syntax:
    content: public int Interval { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: Public Property Interval As Integer
  overload: CronConfigure.Models.Recurrent.Interval*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CronConfigure.Models.Recurrent.#ctor(CronConfigure.Models.Enumeracion.JobType,System.Int32)
  commentId: M:CronConfigure.Models.Recurrent.#ctor(CronConfigure.Models.Enumeracion.JobType,System.Int32)
  id: '#ctor(CronConfigure.Models.Enumeracion.JobType,System.Int32)'
  parent: CronConfigure.Models.Recurrent
  langs:
  - csharp
  - vb
  name: Recurrent(JobType, Int32)
  nameWithType: Recurrent.Recurrent(JobType, Int32)
  fullName: CronConfigure.Models.Recurrent.Recurrent(CronConfigure.Models.Enumeracion.JobType, System.Int32)
  type: Constructor
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Recurrent.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: .ctor
    path: Models/Recurrent.cs
    startLine: 14
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models
  syntax:
    content: public Recurrent(JobType dateType, int interval)
    parameters:
    - id: dateType
      type: CronConfigure.Models.Enumeracion.JobType
    - id: interval
      type: System.Int32
    content.vb: Public Sub New(dateType As JobType, interval As Integer)
  overload: CronConfigure.Models.Recurrent.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CronConfigure.Models
  commentId: N:CronConfigure.Models
  name: CronConfigure.Models
  nameWithType: CronConfigure.Models
  fullName: CronConfigure.Models
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CronConfigure.Models.Recurrent.DateType*
  commentId: Overload:CronConfigure.Models.Recurrent.DateType
  name: DateType
  nameWithType: Recurrent.DateType
  fullName: CronConfigure.Models.Recurrent.DateType
- uid: CronConfigure.Models.Enumeracion.JobType
  commentId: T:CronConfigure.Models.Enumeracion.JobType
  parent: CronConfigure.Models.Enumeracion
  name: JobType
  nameWithType: JobType
  fullName: CronConfigure.Models.Enumeracion.JobType
- uid: CronConfigure.Models.Enumeracion
  commentId: N:CronConfigure.Models.Enumeracion
  name: CronConfigure.Models.Enumeracion
  nameWithType: CronConfigure.Models.Enumeracion
  fullName: CronConfigure.Models.Enumeracion
- uid: CronConfigure.Models.Recurrent.Interval*
  commentId: Overload:CronConfigure.Models.Recurrent.Interval
  name: Interval
  nameWithType: Recurrent.Interval
  fullName: CronConfigure.Models.Recurrent.Interval
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: CronConfigure.Models.Recurrent.#ctor*
  commentId: Overload:CronConfigure.Models.Recurrent.#ctor
  name: Recurrent
  nameWithType: Recurrent.Recurrent
  fullName: CronConfigure.Models.Recurrent.Recurrent
