### YamlMime:ManagedReference
items:
- uid: CronConfigure.Models.Services.CallApiService
  commentId: T:CronConfigure.Models.Services.CallApiService
  id: CallApiService
  parent: CronConfigure.Models.Services
  children:
  - CronConfigure.Models.Services.CallApiService.#ctor(CronConfigure.Models.Services.ConfigUrlService)
  - CronConfigure.Models.Services.CallApiService.CallPostApi(System.String,System.Object)
  langs:
  - csharp
  - vb
  name: CallApiService
  nameWithType: CallApiService
  fullName: CronConfigure.Models.Services.CallApiService
  type: Class
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Services/CallApiService.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: CallApiService
    path: Models/Services/CallApiService.cs
    startLine: 11
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Services
  syntax:
    content: public class CallApiService
    content.vb: Public Class CallApiService
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CronConfigure.Models.Services.CallApiService.#ctor(CronConfigure.Models.Services.ConfigUrlService)
  commentId: M:CronConfigure.Models.Services.CallApiService.#ctor(CronConfigure.Models.Services.ConfigUrlService)
  id: '#ctor(CronConfigure.Models.Services.ConfigUrlService)'
  parent: CronConfigure.Models.Services.CallApiService
  langs:
  - csharp
  - vb
  name: CallApiService(ConfigUrlService)
  nameWithType: CallApiService.CallApiService(ConfigUrlService)
  fullName: CronConfigure.Models.Services.CallApiService.CallApiService(CronConfigure.Models.Services.ConfigUrlService)
  type: Constructor
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Services/CallApiService.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: .ctor
    path: Models/Services/CallApiService.cs
    startLine: 14
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Services
  syntax:
    content: public CallApiService(ConfigUrlService serviceUrl)
    parameters:
    - id: serviceUrl
      type: CronConfigure.Models.Services.ConfigUrlService
    content.vb: Public Sub New(serviceUrl As ConfigUrlService)
  overload: CronConfigure.Models.Services.CallApiService.#ctor*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: CronConfigure.Models.Services.CallApiService.CallPostApi(System.String,System.Object)
  commentId: M:CronConfigure.Models.Services.CallApiService.CallPostApi(System.String,System.Object)
  id: CallPostApi(System.String,System.Object)
  parent: CronConfigure.Models.Services.CallApiService
  langs:
  - csharp
  - vb
  name: CallPostApi(String, Object)
  nameWithType: CallApiService.CallPostApi(String, Object)
  fullName: CronConfigure.Models.Services.CallApiService.CallPostApi(System.String, System.Object)
  type: Method
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Services/CallApiService.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: CallPostApi
    path: Models/Services/CallApiService.cs
    startLine: 19
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Services
  syntax:
    content: public string CallPostApi(string urlMethod, object item)
    parameters:
    - id: urlMethod
      type: System.String
    - id: item
      type: System.Object
    return:
      type: System.String
    content.vb: Public Function CallPostApi(urlMethod As String, item As Object) As String
  overload: CronConfigure.Models.Services.CallApiService.CallPostApi*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: CronConfigure.Models.Services
  commentId: N:CronConfigure.Models.Services
  name: CronConfigure.Models.Services
  nameWithType: CronConfigure.Models.Services
  fullName: CronConfigure.Models.Services
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CronConfigure.Models.Services.CallApiService.#ctor*
  commentId: Overload:CronConfigure.Models.Services.CallApiService.#ctor
  name: CallApiService
  nameWithType: CallApiService.CallApiService
  fullName: CronConfigure.Models.Services.CallApiService.CallApiService
- uid: CronConfigure.Models.Services.ConfigUrlService
  commentId: T:CronConfigure.Models.Services.ConfigUrlService
  parent: CronConfigure.Models.Services
  name: ConfigUrlService
  nameWithType: ConfigUrlService
  fullName: CronConfigure.Models.Services.ConfigUrlService
- uid: CronConfigure.Models.Services.CallApiService.CallPostApi*
  commentId: Overload:CronConfigure.Models.Services.CallApiService.CallPostApi
  name: CallPostApi
  nameWithType: CallApiService.CallPostApi
  fullName: CronConfigure.Models.Services.CallApiService.CallPostApi
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
