### YamlMime:ManagedReference
items:
- uid: CronConfigure
  commentId: N:CronConfigure
  id: CronConfigure
  children:
  - CronConfigure.Program
  - CronConfigure.Startup
  - CronConfigure.WeatherForecast
  langs:
  - csharp
  - vb
  name: CronConfigure
  nameWithType: CronConfigure
  fullName: CronConfigure
  type: Namespace
  assemblies:
  - CronConfigure
references:
- uid: CronConfigure.Program
  commentId: T:CronConfigure.Program
  name: Program
  nameWithType: Program
  fullName: CronConfigure.Program
- uid: CronConfigure.Startup
  commentId: T:CronConfigure.Startup
  name: Startup
  nameWithType: Startup
  fullName: CronConfigure.Startup
- uid: CronConfigure.WeatherForecast
  commentId: T:CronConfigure.WeatherForecast
  name: WeatherForecast
  nameWithType: WeatherForecast
  fullName: CronConfigure.WeatherForecast
