### YamlMime:ManagedReference
items:
- uid: CronConfigure.Models
  commentId: N:CronConfigure.Models
  id: CronConfigure.Models
  children:
  - CronConfigure.Models.EjemploResultado
  - CronConfigure.Models.ErrorViewModel
  - CronConfigure.Models.ExampleService
  - CronConfigure.Models.HangfireEntityContext
  - CronConfigure.Models.Recurrent
  langs:
  - csharp
  - vb
  name: CronConfigure.Models
  nameWithType: CronConfigure.Models
  fullName: CronConfigure.Models
  type: Namespace
  assemblies:
  - CronConfigure
references:
- uid: CronConfigure.Models.EjemploResultado
  commentId: T:CronConfigure.Models.EjemploResultado
  parent: CronConfigure.Models
  name: EjemploResultado
  nameWithType: EjemploResultado
  fullName: CronConfigure.Models.EjemploResultado
- uid: CronConfigure.Models.ErrorViewModel
  commentId: T:CronConfigure.Models.ErrorViewModel
  name: ErrorViewModel
  nameWithType: ErrorViewModel
  fullName: CronConfigure.Models.ErrorViewModel
- uid: CronConfigure.Models.ExampleService
  commentId: T:CronConfigure.Models.ExampleService
  name: ExampleService
  nameWithType: ExampleService
  fullName: CronConfigure.Models.ExampleService
- uid: CronConfigure.Models.HangfireEntityContext
  commentId: T:CronConfigure.Models.HangfireEntityContext
  parent: CronConfigure.Models
  name: HangfireEntityContext
  nameWithType: HangfireEntityContext
  fullName: CronConfigure.Models.HangfireEntityContext
- uid: CronConfigure.Models.Recurrent
  commentId: T:CronConfigure.Models.Recurrent
  name: Recurrent
  nameWithType: Recurrent
  fullName: CronConfigure.Models.Recurrent
- uid: CronConfigure.Models
  commentId: N:CronConfigure.Models
  name: CronConfigure.Models
  nameWithType: CronConfigure.Models
  fullName: CronConfigure.Models
