### YamlMime:ManagedReference
items:
- uid: CronConfigure.Models.Entitties
  commentId: N:CronConfigure.Models.Entitties
  id: CronConfigure.Models.Entitties
  children:
  - CronConfigure.Models.Entitties.JobRepository
  langs:
  - csharp
  - vb
  name: CronConfigure.Models.Entitties
  nameWithType: CronConfigure.Models.Entitties
  fullName: CronConfigure.Models.Entitties
  type: Namespace
  assemblies:
  - CronConfigure
references:
- uid: CronConfigure.Models.Entitties.JobRepository
  commentId: T:CronConfigure.Models.Entitties.JobRepository
  name: JobRepository
  nameWithType: JobRepository
  fullName: CronConfigure.Models.Entitties.JobRepository
