### YamlMime:ManagedReference
items:
- uid: CronConfigure.ViewModels.CreateRecurringJobModel
  commentId: T:CronConfigure.ViewModels.CreateRecurringJobModel
  id: CreateRecurringJobModel
  parent: CronConfigure.ViewModels
  children:
  - CronConfigure.ViewModels.CreateRecurringJobModel.cron_expression
  - CronConfigure.ViewModels.CreateRecurringJobModel.fecha
  - CronConfigure.ViewModels.CreateRecurringJobModel.fecha_inicio
  - CronConfigure.ViewModels.CreateRecurringJobModel.id_repository
  - CronConfigure.ViewModels.CreateRecurringJobModel.nombre_job
  - CronConfigure.ViewModels.CreateRecurringJobModel.set
  langs:
  - csharp
  - vb
  name: CreateRecurringJobModel
  nameWithType: CreateRecurringJobModel
  fullName: CronConfigure.ViewModels.CreateRecurringJobModel
  type: Class
  source:
    remote:
      path: CronConfigure/CronConfigure/ViewModels/CreateRecurringJobModel.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: CreateRecurringJobModel
    path: ViewModels/CreateRecurringJobModel.cs
    startLine: 8
  assemblies:
  - CronConfigure
  namespace: CronConfigure.ViewModels
  syntax:
    content: public class CreateRecurringJobModel
    content.vb: Public Class CreateRecurringJobModel
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CronConfigure.ViewModels.CreateRecurringJobModel.id_repository
  commentId: P:CronConfigure.ViewModels.CreateRecurringJobModel.id_repository
  id: id_repository
  parent: CronConfigure.ViewModels.CreateRecurringJobModel
  langs:
  - csharp
  - vb
  name: id_repository
  nameWithType: CreateRecurringJobModel.id_repository
  fullName: CronConfigure.ViewModels.CreateRecurringJobModel.id_repository
  type: Property
  source:
    remote:
      path: CronConfigure/CronConfigure/ViewModels/CreateRecurringJobModel.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: id_repository
    path: ViewModels/CreateRecurringJobModel.cs
    startLine: 10
  assemblies:
  - CronConfigure
  namespace: CronConfigure.ViewModels
  syntax:
    content: >-
      [Required]

      public string id_repository { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Required>

      Public Property id_repository As String
  overload: CronConfigure.ViewModels.CreateRecurringJobModel.id_repository*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CronConfigure.ViewModels.CreateRecurringJobModel.fecha_inicio
  commentId: P:CronConfigure.ViewModels.CreateRecurringJobModel.fecha_inicio
  id: fecha_inicio
  parent: CronConfigure.ViewModels.CreateRecurringJobModel
  langs:
  - csharp
  - vb
  name: fecha_inicio
  nameWithType: CreateRecurringJobModel.fecha_inicio
  fullName: CronConfigure.ViewModels.CreateRecurringJobModel.fecha_inicio
  type: Property
  source:
    remote:
      path: CronConfigure/CronConfigure/ViewModels/CreateRecurringJobModel.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: fecha_inicio
    path: ViewModels/CreateRecurringJobModel.cs
    startLine: 12
  assemblies:
  - CronConfigure
  namespace: CronConfigure.ViewModels
  syntax:
    content: public string fecha_inicio { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property fecha_inicio As String
  overload: CronConfigure.ViewModels.CreateRecurringJobModel.fecha_inicio*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CronConfigure.ViewModels.CreateRecurringJobModel.fecha
  commentId: P:CronConfigure.ViewModels.CreateRecurringJobModel.fecha
  id: fecha
  parent: CronConfigure.ViewModels.CreateRecurringJobModel
  langs:
  - csharp
  - vb
  name: fecha
  nameWithType: CreateRecurringJobModel.fecha
  fullName: CronConfigure.ViewModels.CreateRecurringJobModel.fecha
  type: Property
  source:
    remote:
      path: CronConfigure/CronConfigure/ViewModels/CreateRecurringJobModel.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: fecha
    path: ViewModels/CreateRecurringJobModel.cs
    startLine: 13
  assemblies:
  - CronConfigure
  namespace: CronConfigure.ViewModels
  syntax:
    content: public string fecha { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property fecha As String
  overload: CronConfigure.ViewModels.CreateRecurringJobModel.fecha*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CronConfigure.ViewModels.CreateRecurringJobModel.set
  commentId: P:CronConfigure.ViewModels.CreateRecurringJobModel.set
  id: set
  parent: CronConfigure.ViewModels.CreateRecurringJobModel
  langs:
  - csharp
  - vb
  name: set
  nameWithType: CreateRecurringJobModel.set
  fullName: CronConfigure.ViewModels.CreateRecurringJobModel.set
  type: Property
  source:
    remote:
      path: CronConfigure/CronConfigure/ViewModels/CreateRecurringJobModel.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: set
    path: ViewModels/CreateRecurringJobModel.cs
    startLine: 14
  assemblies:
  - CronConfigure
  namespace: CronConfigure.ViewModels
  syntax:
    content: public string set { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property set As String
  overload: CronConfigure.ViewModels.CreateRecurringJobModel.set*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CronConfigure.ViewModels.CreateRecurringJobModel.nombre_job
  commentId: P:CronConfigure.ViewModels.CreateRecurringJobModel.nombre_job
  id: nombre_job
  parent: CronConfigure.ViewModels.CreateRecurringJobModel
  langs:
  - csharp
  - vb
  name: nombre_job
  nameWithType: CreateRecurringJobModel.nombre_job
  fullName: CronConfigure.ViewModels.CreateRecurringJobModel.nombre_job
  type: Property
  source:
    remote:
      path: CronConfigure/CronConfigure/ViewModels/CreateRecurringJobModel.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: nombre_job
    path: ViewModels/CreateRecurringJobModel.cs
    startLine: 15
  assemblies:
  - CronConfigure
  namespace: CronConfigure.ViewModels
  syntax:
    content: >-
      [Required]

      public string nombre_job { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Required>

      Public Property nombre_job As String
  overload: CronConfigure.ViewModels.CreateRecurringJobModel.nombre_job*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CronConfigure.ViewModels.CreateRecurringJobModel.cron_expression
  commentId: P:CronConfigure.ViewModels.CreateRecurringJobModel.cron_expression
  id: cron_expression
  parent: CronConfigure.ViewModels.CreateRecurringJobModel
  langs:
  - csharp
  - vb
  name: cron_expression
  nameWithType: CreateRecurringJobModel.cron_expression
  fullName: CronConfigure.ViewModels.CreateRecurringJobModel.cron_expression
  type: Property
  source:
    remote:
      path: CronConfigure/CronConfigure/ViewModels/CreateRecurringJobModel.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: cron_expression
    path: ViewModels/CreateRecurringJobModel.cs
    startLine: 17
  assemblies:
  - CronConfigure
  namespace: CronConfigure.ViewModels
  syntax:
    content: >-
      [Required]

      public string cron_expression { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Required>

      Public Property cron_expression As String
  overload: CronConfigure.ViewModels.CreateRecurringJobModel.cron_expression*
  attributes:
  - type: System.ComponentModel.DataAnnotations.RequiredAttribute
    ctor: System.ComponentModel.DataAnnotations.RequiredAttribute.#ctor
    arguments: []
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CronConfigure.ViewModels
  commentId: N:CronConfigure.ViewModels
  name: CronConfigure.ViewModels
  nameWithType: CronConfigure.ViewModels
  fullName: CronConfigure.ViewModels
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CronConfigure.ViewModels.CreateRecurringJobModel.id_repository*
  commentId: Overload:CronConfigure.ViewModels.CreateRecurringJobModel.id_repository
  name: id_repository
  nameWithType: CreateRecurringJobModel.id_repository
  fullName: CronConfigure.ViewModels.CreateRecurringJobModel.id_repository
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CronConfigure.ViewModels.CreateRecurringJobModel.fecha_inicio*
  commentId: Overload:CronConfigure.ViewModels.CreateRecurringJobModel.fecha_inicio
  name: fecha_inicio
  nameWithType: CreateRecurringJobModel.fecha_inicio
  fullName: CronConfigure.ViewModels.CreateRecurringJobModel.fecha_inicio
- uid: CronConfigure.ViewModels.CreateRecurringJobModel.fecha*
  commentId: Overload:CronConfigure.ViewModels.CreateRecurringJobModel.fecha
  name: fecha
  nameWithType: CreateRecurringJobModel.fecha
  fullName: CronConfigure.ViewModels.CreateRecurringJobModel.fecha
- uid: CronConfigure.ViewModels.CreateRecurringJobModel.set*
  commentId: Overload:CronConfigure.ViewModels.CreateRecurringJobModel.set
  name: set
  nameWithType: CreateRecurringJobModel.set
  fullName: CronConfigure.ViewModels.CreateRecurringJobModel.set
- uid: CronConfigure.ViewModels.CreateRecurringJobModel.nombre_job*
  commentId: Overload:CronConfigure.ViewModels.CreateRecurringJobModel.nombre_job
  name: nombre_job
  nameWithType: CreateRecurringJobModel.nombre_job
  fullName: CronConfigure.ViewModels.CreateRecurringJobModel.nombre_job
- uid: CronConfigure.ViewModels.CreateRecurringJobModel.cron_expression*
  commentId: Overload:CronConfigure.ViewModels.CreateRecurringJobModel.cron_expression
  name: cron_expression
  nameWithType: CreateRecurringJobModel.cron_expression
  fullName: CronConfigure.ViewModels.CreateRecurringJobModel.cron_expression
