### YamlMime:ManagedReference
items:
- uid: CronConfigure.Models.Services
  commentId: N:CronConfigure.Models.Services
  id: CronConfigure.Models.Services
  children:
  - CronConfigure.Models.Services.CallApiService
  - CronConfigure.Models.Services.ConfigUrlService
  - CronConfigure.Models.Services.CronApiService
  - CronConfigure.Models.Services.ICronApiService
  - CronConfigure.Models.Services.IProgramingMethodService
  - CronConfigure.Models.Services.MockCronApiService
  - CronConfigure.Models.Services.MockProgramingMethodService
  - CronConfigure.Models.Services.ProgramingMethodsService
  langs:
  - csharp
  - vb
  name: CronConfigure.Models.Services
  nameWithType: CronConfigure.Models.Services
  fullName: CronConfigure.Models.Services
  type: Namespace
  assemblies:
  - CronConfigure
references:
- uid: CronConfigure.Models.Services.CallApiService
  commentId: T:CronConfigure.Models.Services.CallApiService
  parent: CronConfigure.Models.Services
  name: CallApiService
  nameWithType: CallApiService
  fullName: CronConfigure.Models.Services.CallApiService
- uid: CronConfigure.Models.Services.ConfigUrlService
  commentId: T:CronConfigure.Models.Services.ConfigUrlService
  parent: CronConfigure.Models.Services
  name: ConfigUrlService
  nameWithType: ConfigUrlService
  fullName: CronConfigure.Models.Services.ConfigUrlService
- uid: CronConfigure.Models.Services.CronApiService
  commentId: T:CronConfigure.Models.Services.CronApiService
  name: CronApiService
  nameWithType: CronApiService
  fullName: CronConfigure.Models.Services.CronApiService
- uid: CronConfigure.Models.Services.ICronApiService
  commentId: T:CronConfigure.Models.Services.ICronApiService
  parent: CronConfigure.Models.Services
  name: ICronApiService
  nameWithType: ICronApiService
  fullName: CronConfigure.Models.Services.ICronApiService
- uid: CronConfigure.Models.Services.IProgramingMethodService
  commentId: T:CronConfigure.Models.Services.IProgramingMethodService
  parent: CronConfigure.Models.Services
  name: IProgramingMethodService
  nameWithType: IProgramingMethodService
  fullName: CronConfigure.Models.Services.IProgramingMethodService
- uid: CronConfigure.Models.Services.MockCronApiService
  commentId: T:CronConfigure.Models.Services.MockCronApiService
  name: MockCronApiService
  nameWithType: MockCronApiService
  fullName: CronConfigure.Models.Services.MockCronApiService
- uid: CronConfigure.Models.Services.MockProgramingMethodService
  commentId: T:CronConfigure.Models.Services.MockProgramingMethodService
  name: MockProgramingMethodService
  nameWithType: MockProgramingMethodService
  fullName: CronConfigure.Models.Services.MockProgramingMethodService
- uid: CronConfigure.Models.Services.ProgramingMethodsService
  commentId: T:CronConfigure.Models.Services.ProgramingMethodsService
  name: ProgramingMethodsService
  nameWithType: ProgramingMethodsService
  fullName: CronConfigure.Models.Services.ProgramingMethodsService
- uid: CronConfigure.Models.Services
  commentId: N:CronConfigure.Models.Services
  name: CronConfigure.Models.Services
  nameWithType: CronConfigure.Models.Services
  fullName: CronConfigure.Models.Services
