### YamlMime:ManagedReference
items:
- uid: CronConfigure.Models.Hangfire.JobQueue
  commentId: T:CronConfigure.Models.Hangfire.JobQueue
  id: JobQueue
  parent: CronConfigure.Models.Hangfire
  children:
  - CronConfigure.Models.Hangfire.JobQueue.FetchedAt
  - CronConfigure.Models.Hangfire.JobQueue.Id
  - CronConfigure.Models.Hangfire.JobQueue.JobId
  - CronConfigure.Models.Hangfire.JobQueue.Queue
  langs:
  - csharp
  - vb
  name: JobQueue
  nameWithType: JobQueue
  fullName: CronConfigure.Models.Hangfire.JobQueue
  type: Class
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Hangfire/JobQueue.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: JobQueue
    path: Models/Hangfire/JobQueue.cs
    startLine: 10
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Hangfire
  syntax:
    content: >-
      [Table("jobqueue", Schema = "hangfire")]

      public class JobQueue
    content.vb: >-
      <Table("jobqueue", Schema:="hangfire")>

      Public Class JobQueue
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  attributes:
  - type: System.ComponentModel.DataAnnotations.Schema.TableAttribute
    ctor: System.ComponentModel.DataAnnotations.Schema.TableAttribute.#ctor(System.String)
    arguments:
    - type: System.String
      value: jobqueue
    namedArguments:
    - name: Schema
      type: System.String
      value: hangfire
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: CronConfigure.Models.Hangfire.JobQueue.Id
  commentId: P:CronConfigure.Models.Hangfire.JobQueue.Id
  id: Id
  parent: CronConfigure.Models.Hangfire.JobQueue
  langs:
  - csharp
  - vb
  name: Id
  nameWithType: JobQueue.Id
  fullName: CronConfigure.Models.Hangfire.JobQueue.Id
  type: Property
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Hangfire/JobQueue.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: Id
    path: Models/Hangfire/JobQueue.cs
    startLine: 13
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Hangfire
  syntax:
    content: >-
      [Column(Order = 0)]

      public int Id { get; set; }
    parameters: []
    return:
      type: System.Int32
    content.vb: >-
      <Column(Order:=0)>

      Public Property Id As Integer
  overload: CronConfigure.Models.Hangfire.JobQueue.Id*
  attributes:
  - type: System.ComponentModel.DataAnnotations.Schema.ColumnAttribute
    ctor: System.ComponentModel.DataAnnotations.Schema.ColumnAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Order
      type: System.Int32
      value: 0
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CronConfigure.Models.Hangfire.JobQueue.JobId
  commentId: P:CronConfigure.Models.Hangfire.JobQueue.JobId
  id: JobId
  parent: CronConfigure.Models.Hangfire.JobQueue
  langs:
  - csharp
  - vb
  name: JobId
  nameWithType: JobQueue.JobId
  fullName: CronConfigure.Models.Hangfire.JobQueue.JobId
  type: Property
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Hangfire/JobQueue.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: JobId
    path: Models/Hangfire/JobQueue.cs
    startLine: 16
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Hangfire
  syntax:
    content: public long JobId { get; set; }
    parameters: []
    return:
      type: System.Int64
    content.vb: Public Property JobId As Long
  overload: CronConfigure.Models.Hangfire.JobQueue.JobId*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CronConfigure.Models.Hangfire.JobQueue.Queue
  commentId: P:CronConfigure.Models.Hangfire.JobQueue.Queue
  id: Queue
  parent: CronConfigure.Models.Hangfire.JobQueue
  langs:
  - csharp
  - vb
  name: Queue
  nameWithType: JobQueue.Queue
  fullName: CronConfigure.Models.Hangfire.JobQueue.Queue
  type: Property
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Hangfire/JobQueue.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: Queue
    path: Models/Hangfire/JobQueue.cs
    startLine: 18
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Hangfire
  syntax:
    content: >-
      [Column(Order = 1)]

      [StringLength(50)]

      public string Queue { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: >-
      <Column(Order:=1)>

      <StringLength(50)>

      Public Property Queue As String
  overload: CronConfigure.Models.Hangfire.JobQueue.Queue*
  attributes:
  - type: System.ComponentModel.DataAnnotations.Schema.ColumnAttribute
    ctor: System.ComponentModel.DataAnnotations.Schema.ColumnAttribute.#ctor
    arguments: []
    namedArguments:
    - name: Order
      type: System.Int32
      value: 1
  - type: System.ComponentModel.DataAnnotations.StringLengthAttribute
    ctor: System.ComponentModel.DataAnnotations.StringLengthAttribute.#ctor(System.Int32)
    arguments:
    - type: System.Int32
      value: 50
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: CronConfigure.Models.Hangfire.JobQueue.FetchedAt
  commentId: P:CronConfigure.Models.Hangfire.JobQueue.FetchedAt
  id: FetchedAt
  parent: CronConfigure.Models.Hangfire.JobQueue
  langs:
  - csharp
  - vb
  name: FetchedAt
  nameWithType: JobQueue.FetchedAt
  fullName: CronConfigure.Models.Hangfire.JobQueue.FetchedAt
  type: Property
  source:
    remote:
      path: CronConfigure/CronConfigure/Models/Hangfire/JobQueue.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: FetchedAt
    path: Models/Hangfire/JobQueue.cs
    startLine: 22
  assemblies:
  - CronConfigure
  namespace: CronConfigure.Models.Hangfire
  syntax:
    content: public DateTime? FetchedAt { get; set; }
    parameters: []
    return:
      type: System.Nullable{System.DateTime}
    content.vb: Public Property FetchedAt As Date?
  overload: CronConfigure.Models.Hangfire.JobQueue.FetchedAt*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
references:
- uid: CronConfigure.Models.Hangfire
  commentId: N:CronConfigure.Models.Hangfire
  name: CronConfigure.Models.Hangfire
  nameWithType: CronConfigure.Models.Hangfire
  fullName: CronConfigure.Models.Hangfire
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: CronConfigure.Models.Hangfire.JobQueue.Id*
  commentId: Overload:CronConfigure.Models.Hangfire.JobQueue.Id
  name: Id
  nameWithType: JobQueue.Id
  fullName: CronConfigure.Models.Hangfire.JobQueue.Id
- uid: System.Int32
  commentId: T:System.Int32
  parent: System
  isExternal: true
  name: Int32
  nameWithType: Int32
  fullName: System.Int32
- uid: CronConfigure.Models.Hangfire.JobQueue.JobId*
  commentId: Overload:CronConfigure.Models.Hangfire.JobQueue.JobId
  name: JobId
  nameWithType: JobQueue.JobId
  fullName: CronConfigure.Models.Hangfire.JobQueue.JobId
- uid: System.Int64
  commentId: T:System.Int64
  parent: System
  isExternal: true
  name: Int64
  nameWithType: Int64
  fullName: System.Int64
- uid: CronConfigure.Models.Hangfire.JobQueue.Queue*
  commentId: Overload:CronConfigure.Models.Hangfire.JobQueue.Queue
  name: Queue
  nameWithType: JobQueue.Queue
  fullName: CronConfigure.Models.Hangfire.JobQueue.Queue
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: CronConfigure.Models.Hangfire.JobQueue.FetchedAt*
  commentId: Overload:CronConfigure.Models.Hangfire.JobQueue.FetchedAt
  name: FetchedAt
  nameWithType: JobQueue.FetchedAt
  fullName: CronConfigure.Models.Hangfire.JobQueue.FetchedAt
- uid: System.Nullable{System.DateTime}
  commentId: T:System.Nullable{System.DateTime}
  parent: System
  definition: System.Nullable`1
  name: Nullable<DateTime>
  nameWithType: Nullable<DateTime>
  fullName: System.Nullable<System.DateTime>
  nameWithType.vb: Nullable(Of DateTime)
  fullName.vb: System.Nullable(Of System.DateTime)
  name.vb: Nullable(Of DateTime)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - uid: System.DateTime
    name: DateTime
    nameWithType: DateTime
    fullName: System.DateTime
    isExternal: true
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - uid: System.DateTime
    name: DateTime
    nameWithType: DateTime
    fullName: System.DateTime
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Nullable`1
  commentId: T:System.Nullable`1
  isExternal: true
  name: Nullable<T>
  nameWithType: Nullable<T>
  fullName: System.Nullable<T>
  nameWithType.vb: Nullable(Of T)
  fullName.vb: System.Nullable(Of T)
  name.vb: Nullable(Of T)
  spec.csharp:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: <
    nameWithType: <
    fullName: <
  - name: T
    nameWithType: T
    fullName: T
  - name: '>'
    nameWithType: '>'
    fullName: '>'
  spec.vb:
  - uid: System.Nullable`1
    name: Nullable
    nameWithType: Nullable
    fullName: System.Nullable
    isExternal: true
  - name: '(Of '
    nameWithType: '(Of '
    fullName: '(Of '
  - name: T
    nameWithType: T
    fullName: T
  - name: )
    nameWithType: )
    fullName: )
