### YamlMime:ManagedReference
items:
- uid: CronConfigure.Exceptions
  commentId: N:CronConfigure.Exceptions
  id: CronConfigure.Exceptions
  children:
  - CronConfigure.Exceptions.BadRequestException
  langs:
  - csharp
  - vb
  name: CronConfigure.Exceptions
  nameWithType: CronConfigure.Exceptions
  fullName: CronConfigure.Exceptions
  type: Namespace
  assemblies:
  - CronConfigure
references:
- uid: CronConfigure.Exceptions.BadRequestException
  commentId: T:CronConfigure.Exceptions.BadRequestException
  name: BadRequestException
  nameWithType: BadRequestException
  fullName: CronConfigure.Exceptions.BadRequestException
