### YamlMime:ManagedReference
items:
- uid: API_DISCOVER.Models.Services.ConfigUrlService
  commentId: T:API_DISCOVER.Models.Services.ConfigUrlService
  id: ConfigUrlService
  parent: API_DISCOVER.Models.Services
  children:
  - API_DISCOVER.Models.Services.ConfigUrlService.Configuration
  - API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCarga
  - API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCron
  - API_DISCOVER.Models.Services.ConfigUrlService.UrlCarga
  - API_DISCOVER.Models.Services.ConfigUrlService.UrlCron
  langs:
  - csharp
  - vb
  name: ConfigUrlService
  nameWithType: ConfigUrlService
  fullName: API_DISCOVER.Models.Services.ConfigUrlService
  type: Class
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/Models/Services/ConfigUrlService.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: ConfigUrlService
    path: Models/Services/ConfigUrlService.cs
    startLine: 15
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.Models.Services
  summary: "\nServicio para obtener las variables de configuración de urls\n"
  example: []
  syntax:
    content: public class ConfigUrlService
    content.vb: Public Class ConfigUrlService
  inheritance:
  - System.Object
  inheritedMembers:
  - System.Object.Equals(System.Object)
  - System.Object.Equals(System.Object,System.Object)
  - System.Object.GetHashCode
  - System.Object.GetType
  - System.Object.MemberwiseClone
  - System.Object.ReferenceEquals(System.Object,System.Object)
  - System.Object.ToString
  modifiers.csharp:
  - public
  - class
  modifiers.vb:
  - Public
  - Class
- uid: API_DISCOVER.Models.Services.ConfigUrlService.Configuration
  commentId: P:API_DISCOVER.Models.Services.ConfigUrlService.Configuration
  id: Configuration
  parent: API_DISCOVER.Models.Services.ConfigUrlService
  langs:
  - csharp
  - vb
  name: Configuration
  nameWithType: ConfigUrlService.Configuration
  fullName: API_DISCOVER.Models.Services.ConfigUrlService.Configuration
  type: Property
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/Models/Services/ConfigUrlService.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: Configuration
    path: Models/Services/ConfigUrlService.cs
    startLine: 18
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.Models.Services
  syntax:
    content: public IConfigurationRoot Configuration { get; set; }
    parameters: []
    return:
      type: Microsoft.Extensions.Configuration.IConfigurationRoot
    content.vb: Public Property Configuration As IConfigurationRoot
  overload: API_DISCOVER.Models.Services.ConfigUrlService.Configuration*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: API_DISCOVER.Models.Services.ConfigUrlService.UrlCarga
  commentId: P:API_DISCOVER.Models.Services.ConfigUrlService.UrlCarga
  id: UrlCarga
  parent: API_DISCOVER.Models.Services.ConfigUrlService
  langs:
  - csharp
  - vb
  name: UrlCarga
  nameWithType: ConfigUrlService.UrlCarga
  fullName: API_DISCOVER.Models.Services.ConfigUrlService.UrlCarga
  type: Property
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/Models/Services/ConfigUrlService.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: UrlCarga
    path: Models/Services/ConfigUrlService.cs
    startLine: 19
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.Models.Services
  syntax:
    content: public string UrlCarga { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property UrlCarga As String
  overload: API_DISCOVER.Models.Services.ConfigUrlService.UrlCarga*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: API_DISCOVER.Models.Services.ConfigUrlService.UrlCron
  commentId: P:API_DISCOVER.Models.Services.ConfigUrlService.UrlCron
  id: UrlCron
  parent: API_DISCOVER.Models.Services.ConfigUrlService
  langs:
  - csharp
  - vb
  name: UrlCron
  nameWithType: ConfigUrlService.UrlCron
  fullName: API_DISCOVER.Models.Services.ConfigUrlService.UrlCron
  type: Property
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/Models/Services/ConfigUrlService.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: UrlCron
    path: Models/Services/ConfigUrlService.cs
    startLine: 20
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.Models.Services
  syntax:
    content: public string UrlCron { get; set; }
    parameters: []
    return:
      type: System.String
    content.vb: Public Property UrlCron As String
  overload: API_DISCOVER.Models.Services.ConfigUrlService.UrlCron*
  modifiers.csharp:
  - public
  - get
  - set
  modifiers.vb:
  - Public
- uid: API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCarga
  commentId: M:API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCarga
  id: GetUrlCarga
  parent: API_DISCOVER.Models.Services.ConfigUrlService
  langs:
  - csharp
  - vb
  name: GetUrlCarga()
  nameWithType: ConfigUrlService.GetUrlCarga()
  fullName: API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCarga()
  type: Method
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/Models/Services/ConfigUrlService.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: GetUrlCarga
    path: Models/Services/ConfigUrlService.cs
    startLine: 25
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.Models.Services
  summary: "\nObtiene la url del api de carga que ha sido configurada\n"
  example: []
  syntax:
    content: public string GetUrlCarga()
    return:
      type: System.String
      description: uri del api carga
    content.vb: Public Function GetUrlCarga As String
  overload: API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCarga*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
- uid: API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCron
  commentId: M:API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCron
  id: GetUrlCron
  parent: API_DISCOVER.Models.Services.ConfigUrlService
  langs:
  - csharp
  - vb
  name: GetUrlCron()
  nameWithType: ConfigUrlService.GetUrlCron()
  fullName: API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCron()
  type: Method
  source:
    remote:
      path: API_DISCOVER/API_DISCOVER/Models/Services/ConfigUrlService.cs
      branch: master
      repo: https://github.com/HerculesCRUE/GnossDeustoBackend.git
    id: GetUrlCron
    path: Models/Services/ConfigUrlService.cs
    startLine: 54
  assemblies:
  - API_DISCOVER
  namespace: API_DISCOVER.Models.Services
  summary: "\nObtiene la url del api de carga que ha sido configurada\n"
  example: []
  syntax:
    content: public string GetUrlCron()
    return:
      type: System.String
      description: uri del api cron
    content.vb: Public Function GetUrlCron As String
  overload: API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCron*
  modifiers.csharp:
  - public
  modifiers.vb:
  - Public
references:
- uid: API_DISCOVER.Models.Services
  commentId: N:API_DISCOVER.Models.Services
  name: API_DISCOVER.Models.Services
  nameWithType: API_DISCOVER.Models.Services
  fullName: API_DISCOVER.Models.Services
- uid: System.Object
  commentId: T:System.Object
  parent: System
  isExternal: true
  name: Object
  nameWithType: Object
  fullName: System.Object
- uid: System.Object.Equals(System.Object)
  commentId: M:System.Object.Equals(System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object)
  nameWithType: Object.Equals(Object)
  fullName: System.Object.Equals(System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.Equals(System.Object,System.Object)
  commentId: M:System.Object.Equals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: Equals(Object, Object)
  nameWithType: Object.Equals(Object, Object)
  fullName: System.Object.Equals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.Equals(System.Object,System.Object)
    name: Equals
    nameWithType: Object.Equals
    fullName: System.Object.Equals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetHashCode
  commentId: M:System.Object.GetHashCode
  parent: System.Object
  isExternal: true
  name: GetHashCode()
  nameWithType: Object.GetHashCode()
  fullName: System.Object.GetHashCode()
  spec.csharp:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetHashCode
    name: GetHashCode
    nameWithType: Object.GetHashCode
    fullName: System.Object.GetHashCode
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.GetType
  commentId: M:System.Object.GetType
  parent: System.Object
  isExternal: true
  name: GetType()
  nameWithType: Object.GetType()
  fullName: System.Object.GetType()
  spec.csharp:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.GetType
    name: GetType
    nameWithType: Object.GetType
    fullName: System.Object.GetType
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.MemberwiseClone
  commentId: M:System.Object.MemberwiseClone
  parent: System.Object
  isExternal: true
  name: MemberwiseClone()
  nameWithType: Object.MemberwiseClone()
  fullName: System.Object.MemberwiseClone()
  spec.csharp:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.MemberwiseClone
    name: MemberwiseClone
    nameWithType: Object.MemberwiseClone
    fullName: System.Object.MemberwiseClone
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ReferenceEquals(System.Object,System.Object)
  commentId: M:System.Object.ReferenceEquals(System.Object,System.Object)
  parent: System.Object
  isExternal: true
  name: ReferenceEquals(Object, Object)
  nameWithType: Object.ReferenceEquals(Object, Object)
  fullName: System.Object.ReferenceEquals(System.Object, System.Object)
  spec.csharp:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ReferenceEquals(System.Object,System.Object)
    name: ReferenceEquals
    nameWithType: Object.ReferenceEquals
    fullName: System.Object.ReferenceEquals
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: ', '
    nameWithType: ', '
    fullName: ', '
  - uid: System.Object
    name: Object
    nameWithType: Object
    fullName: System.Object
    isExternal: true
  - name: )
    nameWithType: )
    fullName: )
- uid: System.Object.ToString
  commentId: M:System.Object.ToString
  parent: System.Object
  isExternal: true
  name: ToString()
  nameWithType: Object.ToString()
  fullName: System.Object.ToString()
  spec.csharp:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
  spec.vb:
  - uid: System.Object.ToString
    name: ToString
    nameWithType: Object.ToString
    fullName: System.Object.ToString
    isExternal: true
  - name: (
    nameWithType: (
    fullName: (
  - name: )
    nameWithType: )
    fullName: )
- uid: System
  commentId: N:System
  isExternal: true
  name: System
  nameWithType: System
  fullName: System
- uid: API_DISCOVER.Models.Services.ConfigUrlService.Configuration*
  commentId: Overload:API_DISCOVER.Models.Services.ConfigUrlService.Configuration
  name: Configuration
  nameWithType: ConfigUrlService.Configuration
  fullName: API_DISCOVER.Models.Services.ConfigUrlService.Configuration
- uid: Microsoft.Extensions.Configuration.IConfigurationRoot
  commentId: T:Microsoft.Extensions.Configuration.IConfigurationRoot
  parent: Microsoft.Extensions.Configuration
  isExternal: true
  name: IConfigurationRoot
  nameWithType: IConfigurationRoot
  fullName: Microsoft.Extensions.Configuration.IConfigurationRoot
- uid: Microsoft.Extensions.Configuration
  commentId: N:Microsoft.Extensions.Configuration
  isExternal: true
  name: Microsoft.Extensions.Configuration
  nameWithType: Microsoft.Extensions.Configuration
  fullName: Microsoft.Extensions.Configuration
- uid: API_DISCOVER.Models.Services.ConfigUrlService.UrlCarga*
  commentId: Overload:API_DISCOVER.Models.Services.ConfigUrlService.UrlCarga
  name: UrlCarga
  nameWithType: ConfigUrlService.UrlCarga
  fullName: API_DISCOVER.Models.Services.ConfigUrlService.UrlCarga
- uid: System.String
  commentId: T:System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: API_DISCOVER.Models.Services.ConfigUrlService.UrlCron*
  commentId: Overload:API_DISCOVER.Models.Services.ConfigUrlService.UrlCron
  name: UrlCron
  nameWithType: ConfigUrlService.UrlCron
  fullName: API_DISCOVER.Models.Services.ConfigUrlService.UrlCron
- uid: API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCarga*
  commentId: Overload:API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCarga
  name: GetUrlCarga
  nameWithType: ConfigUrlService.GetUrlCarga
  fullName: API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCarga
- uid: API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCron*
  commentId: Overload:API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCron
  name: GetUrlCron
  nameWithType: ConfigUrlService.GetUrlCron
  fullName: API_DISCOVER.Models.Services.ConfigUrlService.GetUrlCron
