# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.GNOSS_SECRET }}
    - name: Checkout ontology
      uses: actions/checkout@v2
      with:
        repository: HerculesCRUE/GnossDeustoOnto
        ref: 'staging'
        token: ${{ secrets.GNOSS_SECRET }}
        path: roh
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Checkout pellet repo.
      uses: actions/checkout@v2
      with:
          repository: stardog-union/pellet
          path: pellet
    - name: Install Pellet reasoner
      working-directory: pellet
      run: mvn install
    - name: Launch tests
      run: mvn test -DontFile=/home/runner/work/GnossDeustoBackend/GnossDeustoBackend/roh/roh-v2.owl -DdataFile=/home/runner/work/GnossDeustoBackend/GnossDeustoBackend/roh/examples/data.ttl -Duneskos=/home/runner/work/GnossDeustoBackend/GnossDeustoBackend/roh/unesco-individuals.rdf
    - name: Generate surefire-report
      run: mvn surefire-report:report -DontFile=/home/runner/work/GnossDeustoBackend/GnossDeustoBackend/roh/roh-v2.owl -DdataFile=/home/runner/work/GnossDeustoBackend/GnossDeustoBackend/roh/examples/data.ttl -Duneskos=/home/runner/work/GnossDeustoBackend/GnossDeustoBackend/roh/unesco-individuals.rdf
    - name: Generate maven site
      run: mvn site
    - name: Generate documentation
      run: mvn javadoc:test-javadoc
    - name: Deploy github pages
      uses: peaceiris/actions-gh-pages@v3.6.1
      with:
         keep_files: true    
         publish_dir: target/site
         github_token: ${{ secrets.GITHUB_TOKEN }}
